### ISSUE TITLE
whatshap unphase reports an error when PS allows for strings

### ISSUE THREAD

**Issue by marcelm** [whatshap/whatshap#156]
**[Original report](https://bitbucket.org/whatshap/whatshap/issue/156) by Tobias Marschall (Bitbucket: [tobiasmarschall](https://bitbucket.org/tobiasmarschall), GitHub: [tobiasmarschall](https://github.com/tobiasmarschall)).**

----------------------------------------

I just encountered this when working with genome in a bottle data:

```
$ wget -O - ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/NISTv3.3.2/GRCh37/HG002_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-22_v.3.3.2_highconf_triophased.vcf.gz |gunzip | head -n 70 > test.vcf

$ whatshap unphase test.vcf > test.unphased.vcf
Traceback (most recent call last):
  File "/MMCI/TM/structvar/work/marschal/miniconda3/lib/python3.6/site-packages/vcf/parser.py", line 481, in _parse_samples
    sampdat[i] = int(vals)
ValueError: invalid literal for int() with base 10: 'HOMVAR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/MMCI/TM/structvar/work/marschal/miniconda3/bin/whatshap", line 11, in <module>
    load_entry_point('whatshap==0.14.1', 'console_scripts', 'whatshap')()
  File "/MMCI/TM/structvar/work/marschal/miniconda3/lib/python3.6/site-packages/whatshap/__main__.py", line 82, in main
    module.main(args)
  File "/MMCI/TM/structvar/work/marschal/miniconda3/lib/python3.6/site-packages/whatshap/unphase.py", line 69, in main
    remove_phasing(args.vcf, sys.stdout)
  File "/MMCI/TM/structvar/work/marschal/miniconda3/lib/python3.6/site-packages/whatshap/unphase.py", line 40, in remove_phasing
    for record in reader:
  File "/MMCI/TM/structvar/work/marschal/miniconda3/lib/python3.6/site-packages/vcf/parser.py", line 586, in __next__
    samples = self._parse_samples(row[9:], fmt, record)
  File "/MMCI/TM/structvar/work/marschal/miniconda3/lib/python3.6/site-packages/vcf/parser.py", line 483, in _parse_samples
    sampdat[i] = float(vals)
ValueError: could not convert string to float: 'HOMVAR'

$ grep '^##FORMAT=<ID=PS,' test.vcf 
##FORMAT=<ID=PS,Number=1,Type=String,Description="Phase set for GT">
```

Apparently, the parsing does not work despite the fact that the type of PS is set to String in the header. I don't have time to look into this right now, but that might affect other commands beyond `unphase`.

Not sure whether we want to allows phase set IDs to be strings in general. In any case, it would be useful if `unphase` wouldn't fail on this.

**Comment by smajidian** [comment]
Dear WhatsHap team

Thanks for your great tool!
I've faced the same issue. 

I've downloaded the GIAB High confidence [calls](ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh37/HG002_GRCh37_1_22_v4.1_draft_benchmark.vcf.gz) and ran the following line
```
whatshap unphase  HG002_GRCh37_1_22_v4.1_draft_benchmark.vcf.gz > unphase.vcf
```
and faced this
```
Traceback (most recent call last):
  File "/home/ssm/miniconda3/envs/py36/lib/python3.6/site-packages/vcf/parser.py", line 481, in _parse_samples
    sampdat[i] = int(vals)
ValueError: invalid literal for int() with base 10: '16142228_C_T'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ssm/miniconda3/envs/py36/bin/whatshap", line 12, in <module>
    sys.exit(main())
  File "/home/ssm/miniconda3/envs/py36/lib/python3.6/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home/ssm/miniconda3/envs/py36/lib/python3.6/site-packages/whatshap/unphase.py", line 72, in main
    run_unphase(args.vcf, sys.stdout)
  File "/home/ssm/miniconda3/envs/py36/lib/python3.6/site-packages/whatshap/unphase.py", line 43, in run_unphase
    for record in reader:
  File "/home/ssm/miniconda3/envs/py36/lib/python3.6/site-packages/vcf/parser.py", line 586, in __next__
    samples = self._parse_samples(row[9:], fmt, record)
  File "/home/ssm/miniconda3/envs/py36/lib/python3.6/site-packages/vcf/parser.py", line 483, in _parse_samples
    sampdat[i] = float(vals)
ValueError: could not convert string to float: '16142228_C_T'
```
I can guess that the error is originated from the fact that the PS field should be integer (as it is the first pos of phase block).  It would be great if WhatsHap could consider VCF file containing PS field of String format.

There is another issue related to this that I struggle with: when I use  bcftools to combine VCF files (phased+nonphased), it leads to non-asci characters in the output file. It happens when  different field formats for PS tag exist among input files. It forces me to edit the PS manually every time. It would be great that a community-accepted definition will take place in long term. A workaround would be reporting the integer in the PS tag but define it as string in the header to increase the compatibility. 

Also, in The Variant Call Format (VCF) Version 4.2 Specification (page 6), being integer is a recommendation:
```
The recommended convention is to use the position of the first variant in the set as the PS identifier (although this is not required). (Non-negative 32-bit Integer)
```


Regards,
Sina
