### ISSUE TITLE
RuntimeError: Individual with ID 0 not present in pedigree

### ISSUE THREAD

**Issue by marcelm** [whatshap/whatshap#177]
**[Original report](https://bitbucket.org/whatshap/whatshap/issue/177) by Jana Ebler (Bitbucket: [jana_ebler](https://bitbucket.org/jana_ebler), ).**

----------------------------------------

Running whatshap phase with option --ignore-read-groups leads to the following error when providing a BAM-file and phased-blocks VCF as input for phasing:

```
#!shell

... after read selection: 1 non-singleton phased blocks (1 in total)
Variants covered by at least one phase-informative read in at least one individual after read selection: 15
Phasing 1 sample by solving the MEC problem ...
Traceback (most recent call last):
  File "../whatshap/whatshap/venv/bin/whatshap", line 11, in <module>
    load_entry_point('whatshap', 'console_scripts', 'whatshap')()
  File "/MMCI/TM/scratch/colo829/whatshap/whatshap/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/MMCI/TM/scratch/colo829/whatshap/whatshap/whatshap/phase.py", line 1111, in main
    run_whatshap(**vars(args))
  File "/MMCI/TM/scratch/colo829/whatshap/whatshap/whatshap/phase.py", line 863, in run_whatshap
    dp_table = PedigreeDPTable(all_reads, recombination_costs, pedigree, distrust_genotypes, accessible_positions)
  File "whatshap/core.pyx", line 265, in whatshap.core.PedigreeDPTable.__cinit__
RuntimeError: Individual with ID 0 not present in pedigree.

```

**Comment by mylena-s** [comment]
Hello! I found the same error message when using the option --merge-reads. My understanding was that I didn't have to include pedigree information if I wanted to use this option. Is that so? Here the error message:



Skipped 0 groups                                                                                                                   [34/1380]
Found 16863 reads covering 21012 variants                                                                                                   
Kept 14656 reads that cover at least two variants each                                                                                      
Merging 14656 reads with error rate 0.03, maximum error rate 0.05, positive threshold 1000000 and negative threshold 1000 ...               
... after merging: merged 14656 reads into 11202 reads                                                                                      
Selected 11202 most phase-informative reads covering 20930 variants                                                                         
Best-case phasing would result in 628 non-singleton phased blocks (0 singletons).                                                           
Phasing 1 sample by solving the MEC problem ...                                                                                             
Traceback (most recent call last):                                                                                                          
  File "/media/jmf/DATOS2/mylena/assembly_project/miniforge3/envs/whatshap-bbdd29468b35639397f8b50af87d3e92/bin/whatshap", line 10, in <modu
le>
    sys.exit(main())
  File "/media/jmf/DATOS2/mylena/assembly_project/miniforge3/envs/whatshap-bbdd29468b35639397f8b50af87d3e92/lib/python3.10/site-packages/wha
tshap/__main__.py", line 64, in main
    module.main(args)
  File "/media/jmf/DATOS2/mylena/assembly_project/miniforge3/envs/whatshap-bbdd29468b35639397f8b50af87d3e92/lib/python3.10/site-packages/wha
tshap/cli/phase.py", line 1209, in main
    run_whatshap(**vars(args))
  File "/media/jmf/DATOS2/mylena/assembly_project/miniforge3/envs/whatshap-bbdd29468b35639397f8b50af87d3e92/lib/python3.10/site-packages/wha
tshap/cli/phase.py", line 595, in run_whatshap
    dp_table = PedigreeDPTable(
  File "whatshap/core.pyx", line 336, in whatshap.core.PedigreeDPTable.__cinit__
RuntimeError: Individual with ID 0 not present in pedigree.

Thank you!

**Comment by marcelm** [comment]
> I found the same error message when using the option --merge-reads. My understanding was that I didn't have to include pedigree information if I wanted to use this option. Is that so?

No, option `--merge-reads` is not related to pedigree phasing. It is essentially just a way to pre-process the input reads in an attempt to get better phasing results, but it is not so well tested, so I would consider it experimental.

For pedigree phasing, you need to provide a pedigree. If you need more help, I suggest you open a new issue and provide the full command line that you are using (it is easy for us to forget comments made on closed issues).
