### ISSUE TITLE
Polyploid version of whatshap split

### ISSUE THREAD

**Issue by marcelm** [whatshap/whatshap#214]
**[Original report](https://bitbucket.org/whatshap/whatshap/issue/214) by Jana Ebler (Bitbucket: [jana_ebler](https://bitbucket.org/jana_ebler), ).**

----------------------------------------

In order to support higher ploidies, a variable number of output files must be supported \(currently output files are provided using options `--output-h1` and `--output-h2`\).  There is a version \(see branch "polyploid-haplotag"\) that supports additional options `--output-h3` and `--output-h4`, but that only works for ploidies up to 4. @{5c12225d9439134c517c847f} any ideas how to properly extend to higher ploidies?

**Comment by ptrebert** [comment]
preliminary work in branch `dev-feat-polyploid-split`, to be finalized. Jana is going to open a PR for polyploid tagging, and the split branch will be finalized after that.

**Comment by senthilk88** [comment]
Hi I tried to use polyploid-haplotag branch of whatshap to split my tetraploid reads but while trying to install the branch I ended up with the following errors. I have 4 haplotypes and I need tomsplit my reads. 

 whatshap split --output-h1 reads_h1.fastq.gz --output-h2 reads_h2.fastq.gz --output-h3 reads_h3.fastq.gz --output-h4 reads_h4.fastq.gz reads.ccs.fastq.gz reads.tsv --add-untagged --read-lengths-histogram read_length_histogram.tsv

 (base) -bash-4.2$ git checkout polyploid-haplotag
Branch polyploid-haplotag set up to track remote branch polyploid-haplotag from origin.
Switched to a new branch 'polyploid-haplotag'
(base) -bash-4.2$ pip install -e .
Obtaining file:///nfs7/ROOTS/Sathuvalli_Lab/senthil/EVA/haplotype/gatk/bwa-vcf/whatshap
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: pysam>=0.15.0 in /raid1/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages (from whatshap==0.19.dev161+g7660dcf) (0.21.0)
Requirement already satisfied: pyfaidx>=0.5.5.2 in /raid1/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages (from whatshap==0.19.dev161+g7660dcf) (0.7.2.1)
Collecting networkx (from whatshap==0.19.dev161+g7660dcf)
  Using cached networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: biopython>=1.73 in /raid1/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages (from whatshap==0.19.dev161+g7660dcf) (1.78)
Requirement already satisfied: scipy in /raid1/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages (from whatshap==0.19.dev161+g7660dcf) (1.11.2)
Requirement already satisfied: numpy in /raid1/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages (from biopython>=1.73->whatshap==0.19.dev161+g7660dcf) (1.25.2)
Requirement already satisfied: six in /raid1/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages (from pyfaidx>=0.5.5.2->whatshap==0.19.dev161+g7660dcf) (1.16.0)
Requirement already satisfied: setuptools in /raid1/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages (from pyfaidx>=0.5.5.2->whatshap==0.19.dev161+g7660dcf) (68.0.0)
Requirement already satisfied: cython in /raid1/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages (from pysam>=0.15.0->whatshap==0.19.dev161+g7660dcf) (3.0.0)
Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
Building wheels for collected packages: whatshap
  Building editable for whatshap (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building editable for whatshap (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1699 lines of output]
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      running editable_wheel
      creating /data/pip-wheel-f7e1vvfq/.tmp-gree18if/whatshap.egg-info
      writing /data/pip-wheel-f7e1vvfq/.tmp-gree18if/whatshap.egg-info/PKG-INFO
      writing dependency_links to /data/pip-wheel-f7e1vvfq/.tmp-gree18if/whatshap.egg-info/dependency_links.txt
      writing entry points to /data/pip-wheel-f7e1vvfq/.tmp-gree18if/whatshap.egg-info/entry_points.txt
      writing requirements to /data/pip-wheel-f7e1vvfq/.tmp-gree18if/whatshap.egg-info/requires.txt
      writing top-level names to /data/pip-wheel-f7e1vvfq/.tmp-gree18if/whatshap.egg-info/top_level.txt
      writing manifest file '/data/pip-wheel-f7e1vvfq/.tmp-gree18if/whatshap.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'whatshap/core.cpp'
      warning: no files found matching 'whatshap/readselect.cpp'
      warning: no files found matching 'whatshap/priorityqueue.cpp'
      warning: no files found matching 'whatshap/align.cpp'
      warning: no files found matching 'whatshap/_variants.cpp'
      warning: no files found matching 'src/dptable.h'
      warning: no files found matching 'src/columncostcomputer.h'
      adding license file 'LICENSE'
      writing manifest file '/data/pip-wheel-f7e1vvfq/.tmp-gree18if/whatshap.egg-info/SOURCES.txt'
      creating '/data/pip-wheel-f7e1vvfq/.tmp-gree18if/whatshap-0.19.dev161+g7660dcf.dist-info'
      creating /data/pip-wheel-f7e1vvfq/.tmp-gree18if/whatshap-0.19.dev161+g7660dcf.dist-info/WHEEL
      running build_py
      running build_ext
      <string>:54: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      /data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /nfs7/ROOTS/Sathuvalli_Lab/senthil/EVA/haplotype/gatk/bwa-vcf/whatshap/whatshap/_variants.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      /data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /nfs7/ROOTS/Sathuvalli_Lab/senthil/EVA/haplotype/gatk/bwa-vcf/whatshap/whatshap/align.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      /data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /nfs7/ROOTS/Sathuvalli_Lab/senthil/EVA/haplotype/gatk/bwa-vcf/whatshap/whatshap/core.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from libcpp cimport bool
      from libc.stdint cimport uint32_t, uint64_t
      cimport cpp
              ^
 some more errors .........

 Compiling whatshap/core.pyx because it changed.
      Compiling whatshap/priorityqueue.pyx because it changed.
      Compiling whatshap/align.pyx because it changed.
      Compiling whatshap/_variants.pyx because it changed.
      [1/4] Cythonizing whatshap/_variants.pyx
      [2/4] Cythonizing whatshap/align.pyx
      [3/4] Cythonizing whatshap/core.pyx
      Traceback (most recent call last):
        File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 436, in build_editable
          return self._build_with_temp_dir(
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 184, in <module>
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 136, in run
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/data/pip-build-env-602fcwpi/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: whatshap/core.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for whatshap
Failed to build whatshap
ERROR: Could not build wheels for whatshap, which is required to install pyproject.toml-based projects
WARNING: There was an error checking the latest version of pip.

please guide to fix this error

**Comment by schrins** [comment]
The changes of the `polyploid-haplotag` branch have been merged into the main branch some time ago. I guess the branch itself was not merged in git directly, because by the time of the merge it was so far behind the main branch, that it was easier for the developer to redo the changes manually in a new branch. The branch you used has not been updates your years, so I guess some dependencies or libraries broke in the meantime.

Could you try your experiments on the latest release version 2.1 or are there any features missing you need from some old branch?

**Comment by marcelm** [comment]
It appears that while `whatshap haplotag` can indeed work with ploidies greater than 2 (added in PR #410), `whatshap split` cannot.

The old `polyploid-haplotag` contained commit 19dfc085acd541347eee257e7de6769e9f53f3aa, which added support, but it was never merged.

**Comment by marcelm** [comment]
I opened PR #509, which adds support for polyploid `whatshap split` (branch `polyploid-split` in case you want to test it).
