### ISSUE TITLE
pysam error

### ISSUE THREAD

**Issue by KnudNorNielsen** [whatshap/whatshap#254]
The input bam file that apparently causes the problem has been sorted using samtools.
```
$whatshap phase -o phased.vcf --reference=${ref} ${vcf} ${bam}
This is WhatsHap 1.0 running under Python 3.7.8
Traceback (most recent call last):
  File "/home/sjz457/anaconda3/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/sjz457/anaconda3/lib/python3.7/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home/sjz457/anaconda3/lib/python3.7/site-packages/whatshap/cli/phase.py", line 1104, in main
    run_whatshap(**vars(args))
  File "/home/sjz457/anaconda3/lib/python3.7/site-packages/whatshap/cli/phase.py", line 360, in run_whatshap
    indels=indels,
  File "/home/sjz457/anaconda3/lib/python3.7/site-packages/whatshap/cli/__init__.py", line 66, in __init__
    self._bam_paths, reference, numeric_sample_ids, **kwargs,
  File "/home/sjz457/anaconda3/lib/python3.7/site-packages/whatshap/cli/__init__.py", line 27, in open_readset_reader
    readset_reader = ReadSetReader(*args, **kwargs)
  File "/home/sjz457/anaconda3/lib/python3.7/site-packages/whatshap/variants.py", line 61, in __init__
    self._reader = SampleBamReader(paths[0], reference=reference)
  File "/home/sjz457/anaconda3/lib/python3.7/site-packages/whatshap/bam.py", line 51, in __init__
    self._samfile = pysam.AlignmentFile(path, reference_filename=reference)
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 991, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
```

**Comment by tobiasmarschall** [comment]
Does your BAM file have `@SQ` lines in the header? Could you maybe post the header here, i.e. the result of `samtools view -H <file.bam>`?

**Comment by KnudNorNielsen** [comment]
No @SG in the header.

```
$ samtools view -H ${bam}
@HD     VN:1.5  SO:coordinate   pb:3.0.3
@RG     ID:b0a31f1d     SM:ARSEF324     LB:x    PL:PACBIO       PM:SEQUEL       PU:m54071_180310_105846
@PG     ID:baz2bam      PN:baz2bam      VN:5.0.0.6236   CL:/opt/pacbio/ppa-5.0.0/bin/baz2bam /data/pa/m54071_180310_105846.baz -o /data/pa/m54071_180310_105846 --metadata /data/pa/.m54071_180310_105846.metadata.xml -j 12 -b 12 --progress --sil
ent --minSubLength 50 --minSnr 3.750000 --adapters /data/pa/m54071_180310_105846.adapters.fasta --controlAdapters /data/pa/m54071_180310_105846.controls.adapters.fasta --controls /data/pa/m54071_180310_105846.controls.fasta
@PG     ID:bazFormat    PN:bazformat    VN:1.3.0
@PG     ID:bazwriter    PN:bazwriter    VN:5.0.0.6236
@PG     ID:samtools     PN:samtools     PP:baz2bam      VN:1.10 CL:samtools view -H m54071_180310_105846.subreads.bam
@PG     ID:samtools.1   PN:samtools     PP:bazFormat    VN:1.10 CL:samtools view -H m54071_180310_105846.subreads.bam
@PG     ID:samtools.2   PN:samtools     PP:bazwriter    VN:1.10 CL:samtools view -H m54071_180310_105846.subreads.bam
@PG     ID:samtools.3   PN:samtools     PP:samtools     VN:1.10 CL:samtools reheader - m54071_180310_105846.subreads.bam
@PG     ID:samtools.4   PN:samtools     PP:samtools.1   VN:1.10 CL:samtools reheader - m54071_180310_105846.subreads.bam
@PG     ID:samtools.5   PN:samtools     PP:samtools.2   VN:1.10 CL:samtools reheader - m54071_180310_105846.subreads.bam
@PG     ID:samtools.6   PN:samtools     PP:samtools.3   VN:1.10 CL:samtools sort -o m54071_180310_105846.subreads.RG.sort.bam m54071_180310_105846.subreads.RG.bam
@PG     ID:samtools.7   PN:samtools     PP:samtools.4   VN:1.10 CL:samtools sort -o m54071_180310_105846.subreads.RG.sort.bam m54071_180310_105846.subreads.RG.bam
@PG     ID:samtools.8   PN:samtools     PP:samtools.5   VN:1.10 CL:samtools sort -o m54071_180310_105846.subreads.RG.sort.bam m54071_180310_105846.subreads.RG.bam
@PG     ID:samtools.9   PN:samtools     PP:samtools.6   VN:1.10 CL:samtools view -H m54071_180310_105846.subreads.RG.sort.bam
@PG     ID:samtools.10  PN:samtools     PP:samtools.7   VN:1.10 CL:samtools view -H m54071_180310_105846.subreads.RG.sort.bam
@PG     ID:samtools.11  PN:samtools     PP:samtools.8   VN:1.10 CL:samtools view -H m54071_180310_105846.subreads.RG.sort.bam
```

**Comment by marcelm** [comment]
Having no `@SQ` lines in the header is quite unusual. When opening a BAM file, pysam therefore performs a "sanity check" by looking for those `@SQ` lines in the header. So primarily I would suggest that the pipeline that produces these files is broken.

That said, I’m not sure we actually need to have these headers for WhatsHap to work properly. Can you try to disable the check in your copy of WhatsHap? In case you don’t know Python, just edit `/home/sjz457/anaconda3/lib/python3.7/site-packages/whatshap/bam.py` and add a `check_sq=False` in line 51. Before:
```
    self._samfile = pysam.AlignmentFile(path, reference_filename=reference)
```
After:
```
    self._samfile = pysam.AlignmentFile(path, reference_filename=reference, check_sq=False)
```

**Comment by KnudNorNielsen** [comment]
Thank you for the detailed instruction, it was needed.

Rerunning:
```
whatshap phase -o phased.vcf --reference=${ref} ${vcf} ${bam}
This is WhatsHap 1.0 running under Python 3.7.8
ERROR: whatshap error: No reads could be retrieved from 'm54071_180310_105846.subreads.RG.sort.bam'. If this is a CRAM fi
le, possibly the reference could not be found. Try to use --reference=... or check your $REF_PATH/$REF_CACHE setting
```
I don't know what the $REF_CACHE setting is? The 3 input files are in the sam directory, from where I execute.

**Comment by KnudNorNielsen** [comment]
typo, it should have been: 'same directory'

**Comment by marcelm** [comment]
Ok, so that didn’t work.

Do other programs accept the BAM without issues? I’m asking because I tried to create a BAM file without `@SQ` headers just now in order to reproduce your problem, but samtools just refuses:
```
$ samtools view -h tests/data/pacbio/pacbio.bam | grep -v '^@SQ' | samtools view -b -o no-sq.bam -
[E::sam_parse1] no SQ lines present in the header
[W::sam_read1] Parse error at line 4
[main_samview] truncated file.
```

To be honest, I believe the best course of action would be to repair your file.

> I don't know what the $REF_CACHE setting is?

The `$REF_CACHE` environment variable is only relevant for CRAM files, so you can ignore that part of the message.

> typo, it should have been: 'same directory'

Note that you can edit a GitHub comment: Click on the three dots in the top right corner of your comment, then select "Edit".

**Comment by KnudNorNielsen** [comment]
A confession, the error was due to me using the wrong input file. For some reason, I had used the raw bam file from PacBio, instead of the mapped to reference bam file that I had to use. 
Using the correct files, the program ran as perfectly!
I sincerely apologise for the inconvenience and time you dedicated this issue.

**Comment by marcelm** [comment]
No worries, I’m glad to see this resolved!
