### ISSUE TITLE
AssertionError Issue running WhatsHap

### ISSUE THREAD

**Issue by genome2020** [whatshap/whatshap#256]
Hi 
I ran into the following error while trying to run the latest version of WhatsHap. Could you let me know what the issue might be?

This is WhatsHap 1.0 running under Python 3.7.3
Working on 1 samples from 1 family
======== Working on chromosome 'MN985325'
---- Processing individual CAT-114-day11-C_merged_mapping
Using maximum coverage per sample of 15X
Traceback (most recent call last):
  File "/nethome/genome/.local/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/nethome/genome/.local/lib/python3.7/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/nethome/genome/.local/lib/python3.7/site-packages/whatshap/cli/phase.py", line 1104, in main
    run_whatshap(**vars(args))
  File "/nethome/genome/.local/lib/python3.7/site-packages/whatshap/cli/phase.py", line 461, in run_whatshap
    family, include_homozygous, trios, variant_table
  File "/nethome/genome/.local/lib/python3.7/site-packages/whatshap/cli/phase.py", line 744, in find_phaseable_variants
    assert gt.is_diploid_and_biallelic()
AssertionError

**Comment by marcelm** [comment]
Before looking closer into this: Is it possible for you to make the input BAM and VCF files available? That would make it a bit easier. You can send a download link to me at marcel.martin@scilifelab.se and I promise not to share the files.

From the error message, it appears as if a variant that is not diploid or not biallelic is not filtered out when reading in the VCF file. whatshap phase` cannot phase these variants, so it should usually just skip them. Somehow this skipping doesn’t work.

**Comment by marcelm** [comment]
Looking a bit closer, it appears the `is_diploid_and_biallelic()` function checks whether the `GT` field is `0/0`, `0/1` or `1/1`. Perhaps this gives you a hint where to look in case you cannot share the file.

A bit strange is that WhatsHap should already ignore multi-ALT records (in a part of the code that gets executed earlier), so anything like `1/2` should already have been filtered out.

**Comment by peritob** [comment]
Hi and thanks in advance for your help. I am testing this for a workflow.

I am getting same error as this very old @genome2020 issue. Is there a solution for it? 
I checked and vcf/bam headers match. The input.bam and input.vcf were outputs from this pipeline: https://github.com/epi2me-labs/wf-amplicon. These are ONT long amplicons mapped to a reference fasta within wf-amplicon. 
```
whatshap phase --indels --reference=Tc_chr8_NLR.fa input.vcf input.bam -o phased.vcf
WARNING: Ignoring --row-limit as heuristic is not used as algorithm.
WARNING: Ignoring --indels as indel phasing is default in WhatsHap 2.0+
This is WhatsHap 2.3 running under Python 3.9.15
Working on 1 sample from 1 family

# Working on contig T_cacao_A_CHR08_3819933_3826684_ in individual barcode18
Traceback (most recent call last):
  File "/usr/local/whatshap/2.3/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/usr/local/whatshap/2.3/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/usr/local/whatshap/2.3/lib/python3.9/site-packages/whatshap/cli/phase.py", line 1209, in main
    run_whatshap(**vars(args))
  File "/usr/local/whatshap/2.3/lib/python3.9/site-packages/whatshap/cli/phase.py", line 494, in run_whatshap
    homozygous_positions, phasable_variant_table = find_phaseable_variants(
  File "/usr/local/whatshap/2.3/lib/python3.9/site-packages/whatshap/cli/phase.py", line 831, in find_phaseable_variants
    assert gt.is_diploid_and_biallelic()
AssertionError
```

**Comment by tobiasmarschall** [comment]
Thanks for reporting this, @peritob. Would you be able to share short example files to reproduce the error?

**Comment by peritob** [comment]
Further, I reran the mapping with bwa and variant calling with freebayes and the files produced work with whatshap. I suspect something to do with the epi2me wf-amplicon process.
