### ISSUE TITLE
create_read_list_file not implemented in polyphase

### ISSUE THREAD

**Issue by franrodalg** [whatshap/whatshap#269]
Hi everyone,

When I try to ask for the read list using whatshap polyphase I get the following exception:

```Traceback (most recent call last):
  File "[...]/whatshap", line 8, in <module>
    sys.exit(main())
  File "[...]/python3.8/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "[...]/python3.8/site-packages/whatshap/cli/polyphase.py", line 1071, in main
    run_polyphase(**vars(args))
  File "[...]/python3.8/site-packages/whatshap/cli/polyphase.py", line 192, in run_polyphase
    raise NotImplementedError("create_read_list_file not implemented")
NotImplementedError: create_read_list_file not implemented
```

(masking paths)
 is that to be expected?

Cheers,
Fran

**Comment by tobiasmarschall** [comment]
My guess is that the error message is right: That's not implemented. But let @schrins comment on this.

**Comment by schrins** [comment]
Your guess is right, it actually is not implemented. It's also not entirely clear, what the output would be for the polyphase module. The diploid algorithm computes a bipartition of the reads and takes the consensi as haplotypes. So it is very clear which read was used for which haplotype. In polyphase such a k-partition (for ploidy k) does not explicitly exist. One could ...
1. assign the reads to best fitting haplotype afterwards. 
2. take the output of the threading stage, trace back which cluster was moved to which haplotype and add the reads to the list accordingly. However, a part of the reads will not show up on the list (e.g. because it ended up in a noise cluster which was discarded) and multiple haplotypes could have been threaded through the same cluster, which makes the mapping from clusters to haplotypes non-unique.

This requires some discussion before we can implement this feature.

**Comment by franrodalg** [comment]
Thanks for your reply. I suppose that the polyphase's help should be amended, then, since it lists `--output-read-list` as valid argument:

```
usage: whatshap polyphase [-h] [-o OUTPUT] [--reference FASTA] [--tag {PS,HP}] [--output-read-list FILE]
                          [--mapping-quality QUAL] [--indels] [--ignore-read-groups] [--sample SAMPLE]
                          [--chromosome CHROMOSOME] [--verify-genotypes] --ploidy PLOIDY [--min-overlap OVERLAP]
                          [--ce-refinements REFINEMENTS] [--block-cut-sensitivity SENSITIVITY]
                          VCF [PHASEINPUT [PHASEINPUT ...]]
```

```
  --output-read-list FILE
                        Write reads that have been used for phasing to FILE.
```

I will then need to try and find a way of calling "haplotypes" for multicopy regions myself, at least until you manage to find a way to implement it here.

Thanks anyway :)
