### ISSUE TITLE
Error parsing GVCFs with dot in ALT column

### ISSUE THREAD

**Issue by rhysf** [whatshap/whatshap#289]
Hi, i've just tried running whatsapp after downloading it on Conda as recommended. My command is:

whatshap phase -o isolate1/phased.vcf --reference=ref/genome.fasta isolate1/isolate1.vcf  isolate1/isolate1.bam

My VCF is from GATK HaplotypeCaller and my BAM is from BWA-mem. My output is:

This is WhatsHap 1.0 running under Python 3.8.5
Working on 1 samples from 1 family
Traceback (most recent call last):
  File "/Users/me/miniconda3/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/Users/me/miniconda3/lib/python3.8/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/Users/me/miniconda3/lib/python3.8/site-packages/whatshap/cli/phase.py", line 1104, in main
    run_whatshap(**vars(args))
  File "/Users/me/miniconda3/lib/python3.8/site-packages/whatshap/cli/phase.py", line 414, in run_whatshap
    for variant_table in timers.iterate("parse_vcf", vcf_reader):
  File "/Users/me/miniconda3/lib/python3.8/site-packages/whatshap/timer.py", line 51, in iterate
    for item in iterator:
  File "/Users/me/miniconda3/lib/python3.8/site-packages/whatshap/vcf.py", line 398, in __iter__
    yield self._process_single_chromosome(chromosome, records)
  File "/Users/me/miniconda3/lib/python3.8/site-packages/whatshap/vcf.py", line 431, in _process_single_chromosome
    if len(record.alts) > 1:
TypeError: object of type 'NoneType' has no len()

I've tried it on some other VCF's and BAM's I have and have the same issue?
Any assistance greatly appreciated. Thanks,

**Comment by tobiasmarschall** [comment]
On first sight, it sounds there's something wrong the `ALT` column in your VCF. Would it be possible to share a small VCF that triggers the problem? Can you "view" the VCF with `bcftools view`? (Or does that result in any errors/warnings that might give you hints?)

**Comment by rhysf** [comment]
Thanks for your very fast response.

bcftools view seems to work fine. As suggested, I did the following:

head -200 sample.vcf > head.vcf

and re-run, and still got the same error.

I have attached that VCF.

[head.vcf.zip](https://github.com/whatshap/whatshap/files/6069803/head.vcf.zip)

**Comment by tobiasmarschall** [comment]
Ok, that seem to be a "GVCF" and our VCF parsing is thrown off by the `.` in the `ALT` column. I think we should fix that. In the interim you might try removing all lines that have a `.` in the `ALT` column and rerun.

**Comment by rhysf** [comment]
Great! Thanks for your help.

**Comment by tobiasmarschall** [comment]
Let's keep this open to remind us to fix this.
