### ISSUE TITLE
TypeError when using --distrust-genotypes

### ISSUE THREAD

**Issue by Yiguan** [whatshap/whatshap#293]
When I use argument `--distrust-genotype` in the command as following: 
```
whatshap phase --ped ../../samples_sub.ped --distrust-genotypes --recombrate 2.32 \
    -o chr_4.pedigree.distrust-genotypes.phased.vcf.gz \
    --reference=dmel-all-chromosome-r6.36.fasta \
    ../4.vcf.gz ../*bam
```

I will receive an error: 

```
This is WhatsHap 1.0 running under Python 3.6.8
Using uniform recombination rate of 2.32 cM/Mb.
Working on 7s samples from 1 family
WARNING: The maximum coverage is too high! WhatsHap may take a long time to finish and require a huge amount of memory.
Traceback (most recent call last):
  File "/data/home/ywang120/.local/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/data/home/ywang120/.local/lib/python3.6/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/data/home/ywang120/.local/lib/python3.6/site-packages/whatshap/cli/phase.py", line 1104, in main
    run_whatshap(**vars(args))
  File "/data/home/ywang120/.local/lib/python3.6/site-packages/whatshap/cli/phase.py", line 414, in run_whatshap
    for variant_table in timers.iterate("parse_vcf", vcf_reader):
  File "/data/home/ywang120/.local/lib/python3.6/site-packages/whatshap/timer.py", line 51, in iterate
    for item in iterator:
  File "/data/home/ywang120/.local/lib/python3.6/site-packages/whatshap/vcf.py", line 398, in __iter__
    yield self._process_single_chromosome(chromosome, records)
  File "/data/home/ywang120/.local/lib/python3.6/site-packages/whatshap/vcf.py", line 509, in _process_single_chromosome
    genotype_likelihoods.append(GenotypeLikelihoods([pl / -10 for pl in PL]))
  File "/data/home/ywang120/.local/lib/python3.6/site-packages/whatshap/vcf.py", line 509, in <listcomp>
    genotype_likelihoods.append(GenotypeLikelihoods([pl / -10 for pl in PL]))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```
If I don't include `--distrust-genotypes`, there isn't any error. I think the `--distrust-genotypes` causes the error.

I am not use if I made some mistakes or somewhere wrong in the code. 
Thanks!

**Comment by tobiasmarschall** [comment]
Could you send a few lines from your input VCF? The error sounds like there's a problem parsing the genotype likelihoods in it. I don't fully remember, but I think we discussed the combination of `--distrust-genotypes` and pedigree mode a long while ago. @eblerjana Do you remember this?

**Comment by Yiguan** [comment]
Thanks for such a quick response.
Here are a few lines in the VCF file I used:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample_43       sample_32       sample_62       sample_74       sample_75       sample_79       sample_84
4       434     .       C       T       1318.68 .       AC=2;AN=8       GT:AD:DP:GQ:PGT:PID:PL  0/0:14,0:14:30:.:.:0,30,450     1/1:0,23:23:72:1|1:434_C_T:1076,72,0    ./.:0,0:0:.:.:.:0,0,0   0/0:2,0:2:0:.:.:0,0,2      ./.:3,0:3:.:.:.:0,0,0   ./.:3,0:3:.:.:.:0,0,0   0/0:6,0:6:0:.:.:0,0,178
4       443     .       T       G       1418.19 .       AC=2;AN=8       GT:AD:DP:GQ:PGT:PID:PL  0/0:9,0:9:21:.:.:0,21,315       1/1:0,24:24:75:1|1:434_C_T:1108,75,0    ./.:0,0:0:.:.:.:0,0,0   0/0:1,0:1:3:.:.:0,3,44     ./.:3,0:3:.:.:.:0,0,0   ./.:3,0:3:.:.:.:0,0,0   0/0:4,0:4:0:.:.:0,0,91
4       3321    .       G       T       4501.05 .       AC=7;AN=14      GT:AD:DP:GQ:PL  0/0:23,0:23:45:0,45,675 1/1:0,32:32:96:1278,96,0        0/1:8,8:16:99:261,0,272 0/1:5,8:13:99:284,0,178 0/1:11,8:19:99:261,0,425   0/1:8,6:14:99:202,0,309 0/1:5,6:11:99:214,0,169
4       5061    .       T       C       2538.05 .       AC=7;AN=14      GT:AD:DP:GQ:PL  1/1:0,12:12:36:524,36,0 0/0:41,0:41:99:0,99,1485        0/1:9,2:11:46:46,0,316  0/1:8,8:16:99:298,0,279 0/1:5,3:8:99:109,0,180     0/1:6,8:14:99:297,0,185 0/1:13,5:18:99:147,0,463
4       5233    .       T       A       1145.36 .       AC=4;AN=14      GT:AD:DP:GQ:PL  0/0:16,0:16:48:0,48,640 0/1:17,8:25:99:244,0,607        0/1:6,3:9:99:103,0,217  0/1:5,7:12:99:253,0,175 0/0:10,0:10:30:0,30,414    0/0:15,0:15:42:0,42,630 0/1:3,3:6:70:70,0,94
4       5377    .       A       T       2430.92 .       AC=7;AN=14      GT:AD:DP:GQ:PL  1/1:0,12:12:36:519,36,0 0/0:17,0:17:45:0,45,675 0/1:7,3:10:99:104,0,262 0/1:5,4:9:99:146,0,174  0/1:3,8:11:99:307,0,99     0/1:2,10:12:33:380,0,33 0/1:3,2:5:63:63,0,99
4       5480    .       G       C       258.31  .       AC=5;AN=8       GT:AD:DP:GQ:PL  ./.:0,0:0:.:0,0,0       0/1:1,2:3:23:55,0,23    1/1:0,2:2:6:63,6,0      ./.:1,0:1:.:0,0,0       ./.:0,0:0:.:0,0,0 0/0:1,0:1:3:0,3,29       1/1:0,2:2:6:64,6,0
4       6342    .       T       A       1830.93 .       AC=5;AN=14      GT:AD:DP:GQ:PL  0/0:20,0:20:48:0,48,720 1/1:0,17:17:51:718,51,0 0/1:11,9:20:99:313,0,399        0/1:9,4:13:99:126,0,346 0/0:6,0:6:18:0,18,219      0/0:11,0:11:33:0,33,449 0/1:7,8:15:99:284,0,253
4       7223    .       G       A       2363.36 .       AC=6;AN=14      GT:AD:DP:GQ:PL  0/0:11,0:11:33:0,33,459 0/1:5,10:15:99:313,0,153        0/1:4,8:12:99:227,0,110 0/1:8,9:17:99:282,0,216 0/1:5,3:8:75:75,0,149      0/1:12,6:18:99:131,0,310        0/1:6,7:13:99:165,0,151
4       7722    .       A       G       672.38  .       AC=6;AN=14      GT:AD:DP:GQ:PL  0/0:20,0:20:60:0,60,826 1/1:0,6:6:18:214,18,0   0/1:12,2:14:47:47,0,453 0/0:16,0:16:2:0,2,604   0/1:24,2:26:1:1,0,870      0/1:11,3:14:62:62,0,370 0/1:9,5:14:99:122,0,323

```

Please let me know if further data are needed!

**Comment by marcelm** [comment]
I’m sorry this took so long, but the problem should now be fixed. The crash occurred when the value for the `PL` field (phred-scaled genotype likelihoods) contains a dot, as in `15,.,18`.
