### ISSUE TITLE
WhatsHap haplotag error - int() argument

### ISSUE THREAD

**Issue by skambha6** [whatshap/whatshap#301]
Hi,

I'm trying to run WhatsHap Haplotag, but the following error appears:

```
Found 1 samples in input VCF
Keeping 1 samples for haplo-tagging
Found 1 samples in BAM file
Traceback (most recent call last):
  File "/home-4/skambha6@jhu.edu/.local/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home-4/skambha6@jhu.edu/.local/lib/python3.8/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home-4/skambha6@jhu.edu/.local/lib/python3.8/site-packages/whatshap/cli/haplotag.py", line 594, in main
    run_haplotag(**vars(args))
  File "/home-4/skambha6@jhu.edu/.local/lib/python3.8/site-packages/whatshap/cli/haplotag.py", line 530, in run_haplotag
    (BX_tag_to_haplotype, read_to_haplotype, n_mult) = prepare_haplotag_information(
  File "/home-4/skambha6@jhu.edu/.local/lib/python3.8/site-packages/whatshap/cli/haplotag.py", line 173, in prepare_haplotag_information
    variantpos_to_phaseinfo, variants = get_variant_information(variant_table, sample)
  File "/home-4/skambha6@jhu.edu/.local/lib/python3.8/site-packages/whatshap/cli/haplotag.py", line 89, in get_variant_information
    phase_info = int(phases[idx].block_id), phases[idx].phase[0]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
```

Any advice on how to resolve this error would be appreciated.

Thank you!
Sandeep

**Comment by marcelm** [comment]
Hi, this has been reported before in issue #249. It has already been fixed in the development branch, but we have not made a new release, yet. You can install the development version of WhatsHap to get the fixed version, but I think it is also time for us to prepare a new release, which I can perhaps do today.

**Comment by marcelm** [comment]
WhatsHap 1.1 is now available on PyPI (for `pip install`). The Bioconda package should be updated soon as well.

For the developers reading here: Preparing a release is now as simple as creating a tag and pushing it. The rest will be done automatically in a GitHub Actions job. See <https://whatshap.readthedocs.io/en/latest/develop.html#making-a-release>.
