### ISSUE TITLE
--hapchat mode Assertion Error/--distrust_genotypes changes file off by one error?

### ISSUE THREAD

**Issue by noahrose** [whatshap/whatshap#305]
I have been trying out the --hapchat mode to try to reduce runtimes with some data from large highly polymorphic chromosomes and I have been getting an error that I don't get with the standard algorithm on the same data:

======== Writing VCF
Done writing VCF
Traceback (most recent call last):
  File "/home/noahr/miniconda3/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/noahr/miniconda3/lib/python3.7/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home/noahr/miniconda3/lib/python3.7/site-packages/whatshap/cli/phase.py", line 1104, in main
    run_whatshap(**vars(args))
  File "/home/noahr/miniconda3/lib/python3.7/site-packages/whatshap/cli/phase.py", line 643, in run_whatshap
    assert distrust_genotypes
AssertionError

I reran the command using distrust_genotypes and writing the changed genotypes to a file and it now works. I just wanted to confirm that this is the expected behavior -- i.e. does HapChat inherently need to run with the ability to change genotypes because of its error correction algorithm? If so it could be useful to automatically enable distrust_genotypes with the hapchat algorithm and give some sort of warning to the user? Apologies if I am misunderstanding, and please do let me know if this is not the expected behavior.

Also, I think there may be an off-by-one error in the positions given in the changes file  -- the positions in the changes file all correspond to positions of low quality heterozygous variants -1 base (presumably zero-based indexing). Again, apologies if I am misunderstanding something here.

e.g. changes file:
Debug023_aegypti_Bantata_Senegal_M_7    NC_035107.1     264008305       C       T       0/1     0/0
Debug023_aegypti_Bantata_Senegal_M_7    NC_035107.1     264008310       G       A       0/1     0/0

bcftools view -H prephase_samples_hapchat/Debug023_aegypti_Bantata_Senegal_M_7_prephase.bcf | grep '2640083' | head | cut -f 1,2,4,5,10 
NC_035107.1     264008306       C       T       0/0:68,6,0:2:0,2:15:.
NC_035107.1     264008311       G       A       0/0:37,3,0:1:0,1:5:.

**Comment by murraypatterson** [comment]
Since the core algorithm/implementation of Hapchat was able to change the genotype by default before it was integrated into the Whatshap framework, my guess is that does not support the "trust genotype" flag now that is has been integrated into Whatshap.  I believe that this is also impossible because of the inherent properties of its error correction algorithm as you point out above, but I am not sure.  I could look into it, if you wish

**Comment by noahrose** [comment]
Thanks for your quick response, that all makes sense -- it's not so much that I was hoping to make hapchat trust genotypes as that I wanted to understand the cause of the error. I do think it would be helpful for the end user if you had some sort of warning rather than having the program error out in this case (since the default behavior is to trust genotypes, so it is easy to specify --algorithm hapchat without knowing that you have to ALSO specify --distrust-genotypes in order for the program to run without an error). But it's easy enough to just run it with both options now that I know!

**Comment by murraypatterson** [comment]
I completely agree --- I think it is clear what the issue is now --- thanks for opening this
