### ISSUE TITLE
Phasing with duos

### ISSUE THREAD

**Issue by christianfiles** [whatshap/whatshap#311]
Hi, 

My main question... Can `whatshap phase` be used on duos as well as trios?

I have been using the whatshap tool for trios successfully using `whatshap phase`, however, when I try to remove one of the samples so I am left with proband and one parent I get the following error message:
`Traceback (most recent call last):
  File "/home/.local/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/home/.local/lib/python3.8/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home/.local/lib/python3.8/site-packages/whatshap/cli/phase.py", line 1107, in main
    run_whatshap(**vars(args))
  File "/home/.local/lib/python3.8/site-packages/whatshap/cli/phase.py", line 418, in run_whatshap
    for variant_table in timers.iterate("parse_vcf", vcf_reader):
  File "/home/.local/lib/python3.8/site-packages/whatshap/timer.py", line 51, in iterate
    for item in iterator:
  File "/home/.local/lib/python3.8/site-packages/whatshap/vcf.py", line 430, in __iter__
    yield self._process_single_chromosome(chromosome, records)
  File "/home/.local/lib/python3.8/site-packages/whatshap/vcf.py", line 564, in _process_single_chromosome
    raise PloidyError(
whatshap.vcf.PloidyError: Inconsistent ploidy (2 and 1)`

The full command for the trio that works was:
`whatshap phase -o $HOME/phased.vcf --reference=/data/resources/human/mappers/b37/bwa/human_g1k_v37.fasta /data/output/results/run.norm.anno.vcf.gz /data/output/results/sample1.bam /data/output/results/sample2.bam /data/output/results/sample3.bam --chromosome 20 --ped /data/output/results/run.ped
`

I then used a mix of vcftools and bcftools to remove sample3 and compressed (using bgzip) and indexed this new vcf.
I also removed this sample from the run.ped file.

The new command looked like the following:
`whatshap phase -o ~/whatshap/duo/phased.vcf --reference=/data/resources/human/mappers/b37/bwa/human_g1k_v37.fasta ~/whatshap/duo/run.recode.vcf.gz /data/output/results/sample1.bam /data/output/results/sample2.bam --chromosome 20 --ped ~/whatshap/duo/run.ped
`

And that is when I get the `PloidyError` thrown my way.

Any clarification on this would be much appreciated.

Many thanks,
Chris

**Comment by schrins** [comment]
I cannot answer your question whether phasing on duos works. I just know that this was not supported some time ago. However, the error message is misleading to say the least. I assume you did not get it with a full trio? Besides from your actual question, could you maybe share one line of your VCF input containing a heterozyguous variant? If this error is caused by duos not being supported, it should at least output a proper error message.

**Comment by christianfiles** [comment]
Thanks for the advice. I will try the "dummy parent" approach

**Comment by christianfiles** [comment]
I tried the "dummy" approach. Added the dummy sample to the vcf with all genotypes set to heterozygous and added it to the ped file and I am still getting the same error as before with the inconsistent ploidy... 
Have you tried this approach previously?

**Comment by schrins** [comment]
I looked at the source code. The only way to get to this error message seems to be a line in the VCF file, where the GT-field contains only one allele. The error occurs at a stage, where the VCF is read to determine where the heterozyguous variants are. In the line you posted, everything seems to be fine. Can you maybe check whether all GT-fields are of length 2 (either "0/0", "0/1" or "1/1") or provide a small example VCF which triggers this error? (BAM files are not needed)

**Comment by christianfiles** [comment]
I checked the GT field for all samples in the vcf with the following command:
`bcftools query -f '[\t%SAMPLE=%GT]\n' example.vcf.gz | grep "=.$"` 
I got nothing returned, which suggests that it could not find a GT with only only one allele

As a sanity check, I did run `bcftools query -f '[\t%SAMPLE=%GT]\n' example.vcf.gz | grep "=0/1$"` to check it worked and it pulled out samples with that genotype.

**Comment by tobiasmarschall** [comment]
Would you be able to share a (preferably small) example that triggers this error?

**Comment by christianfiles** [comment]
So I think I have realised why this is not working. I have given whatshap a full vcf specifying `--chromosome 20`, which I believe should just run on chromosome 20. 

When I take chromosome 20 from the vcf file beforehand using `bcftools` and then run whatshap without the `--chromosome 20` flag then the tool works.

**Comment by hurrialice** [comment]
> Duos are presently not implemented. I recall a discussion on this, but I cannot find back the corresponding issue. A hacky workaround if you only have a duo, is to add one "dummy parent" with all genotypes set to heterozygous and remove it again after phasing...

Hey, may I confirm it's still the recommended approach to phase duo as of June 2022? Thanks again for your advice!
