### ISSUE TITLE
Longshot generated VCF not working

### ISSUE THREAD

**Issue by B10inform** [whatshap/whatshap#321]
Hi,

Does whatshap works with the vcf file generated by longshot? I am getting following error.
my command:  whatshap phase --ignore-read-groups --reference Asm.pa_ctg.fasta Asm.pa_ctg_bwa_sorted_longshot.vcf.gz Asm.pa_ctg_bwa_HiFi_sorted.bam -o Asm.pa_ctg_bwa_sorted_longshot_phased.vcf.gz

**Error:**
This is WhatsHap 1.1.dev91+gc714ed5 running under Python 3.7.4
Working on 1 samples from 1 family
======== Working on chromosome 'ptg000003l'
---- Processing individual SAMPLE
Using maximum coverage per sample of 15X
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 272
Reading alignments and detecting alleles ...
Found 485 reads covering 272 variants
Kept 98 reads that cover at least two variants each
Reducing coverage to at most 15X by selecting most informative reads ...
Selected 68 reads covering 259 variants
Best-case phasing would result in 5 non-singleton phased blocks (5 in total)
... after read selection: 5 non-singleton phased blocks (5 in total)
Variants covered by at least one phase-informative read in at least one individual after read selection: 259
Phasing 1 sample by solving the MEC problem ...
MEC cost: 3840
No. of phased blocks: 5
Largest block contains 247 variants (95.4% of accessible variants) between position 13307 and 23353
======== Writing VCF
[E::vcf_parse_format] Invalid character '.' in 'GQ' FORMAT field at ptg000003l:13085
Traceback (most recent call last):
  File "/home/.local/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/home/.local/lib/python3.7/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home/.local/lib/python3.7/site-packages/whatshap/cli/phase.py", line 1128, in main
    run_whatshap(**vars(args))
  File "/home/.local/lib/python3.7/site-packages/whatshap/cli/phase.py", line 594, in run_whatshap
    changed_genotypes = vcf_writer.write(chromosome, superreads, components)
  File "/home/.local/lib/python3.7/site-packages/whatshap/vcf.py", line 966, in write
    for record in self._iterrecords(chromosome):
  File "/home/.local/lib/python3.7/site-packages/whatshap/vcf.py", line 833, in _iterrecords
    for record in self._reader_iter:
  File "pysam/libcbcf.pyx", line 4108, in pysam.libcbcf.VariantFile.__next__
OSError: unable to parse next record

**My VCF file:**
#fileformat=VCFv4.2
##source=Longshot v0.4.0
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth of reads passing MAPQ filter">
##INFO=<ID=AC,Number=R,Type=Integer,Description="Number of Observations of Each Allele">
##INFO=<ID=AM,Number=1,Type=Integer,Description="Number of Ambiguous Allele Observations">
##INFO=<ID=MC,Number=1,Type=Integer,Description="Minimum Error Correction (MEC) for this single variant">
##INFO=<ID=MF,Number=1,Type=Float,Description="Minimum Error Correction (MEC) Fraction for this variant.">
##INFO=<ID=MB,Number=1,Type=Float,Description="Minimum Error Correction (MEC) Fraction for this variant's haplotype block.">
##INFO=<ID=AQ,Number=1,Type=Float,Description="Mean Allele Quality value (PHRED-scaled).">
##INFO=<ID=GM,Number=1,Type=Integer,Description="Phased genotype matches unphased genotype (boolean).">
##INFO=<ID=DA,Number=1,Type=Integer,Description="Total Depth of reads at any MAPQ (but passing samtools filter 0xF00).">
##INFO=<ID=MQ10,Number=1,Type=Float,Description="Fraction of reads (passing 0xF00) with MAPQ>=10.">
##INFO=<ID=MQ20,Number=1,Type=Float,Description="Fraction of reads (passing 0xF00) with MAPQ>=20.">
##INFO=<ID=MQ30,Number=1,Type=Float,Description="Fraction of reads (passing 0xF00) with MAPQ>=30.">
##INFO=<ID=MQ40,Number=1,Type=Float,Description="Fraction of reads (passing 0xF00) with MAPQ>=40.">
##INFO=<ID=MQ50,Number=1,Type=Float,Description="Fraction of reads (passing 0xF00) with MAPQ>=50.">
##INFO=<ID=PH,Number=G,Type=Integer,Description="PHRED-scaled Probabilities of Phased Genotypes">
##INFO=<ID=SC,Number=1,Type=String,Description="Reference Sequence in 21-bp window around variant.">
##FILTER=<ID=dn,Description="In a dense cluster of variants">
##FILTER=<ID=dp,Description="Exceeds maximum depth">
##FILTER=<ID=sb,Description="Allelic strand bias">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Float,Description="Genotype Quality">
##FORMAT=<ID=PS,Number=1,Type=Integer,Description="Phase Set">
##FORMAT=<ID=UG,Number=1,Type=String,Description="Unphased Genotype (pre-haplotype-assembly)">
##FORMAT=<ID=UQ,Number=1,Type=Float,Description="Unphased Genotype Quality (pre-haplotype-assembly)">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE
ptg000002l	31726	.	G	T	19.59	PASS	DP=12;AC=9,3;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=29;MQ10=0.72;MQ20=0.69;MQ30=0.41;MQ40=0.41;MQ50=0.38;PH=19.59,3.06,3.06,238.12;SC=GGCCTATTTTGTACCACACGG;	GT:GQ:PS:UG:UQ	0/1:19.59:.:0/1:19.59
ptg000002l	37154	.	G	T	34.57	PASS	DP=9;AC=4,3;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=44;MQ10=0.39;MQ20=0.23;MQ30=0.20;MQ40=0.11;MQ50=0.09;PH=34.57,3.01,3.01,102.47;SC=GGCCTATTTTGTACCACACGG;	GT:GQ:PS:UG:UQ	0/1:34.57:.:0/1:34.57
ptg000002l	53824	.	G	C	8.31	PASS	DP=6;AC=2,3;AM=1;MC=1;MF=0.200;MB=0.200;AQ=10.96;GM=1;DA=30;MQ10=0.27;MQ20=0.23;MQ30=0.20;MQ40=0.13;MQ50=0.10;PH=8.31,0.83,37.16,15.98;SC=GGCGGACGAAGTTGGCCAACC;	GT:GQ:PS:UG:UQ	0|1:7.62:53824:0/1:39.87
ptg000002l	53832	.	A	G	9.74	PASS	DP=6;AC=2,3;AM=1;MC=1;MF=0.200;MB=0.200;AQ=10.63;GM=1;DA=33;MQ10=0.24;MQ20=0.21;MQ30=0.18;MQ40=0.12;MQ50=0.09;PH=9.74,2.17,38.50,5.43;SC=AAGTTGGCCAACCCCACCCCC;	GT:GQ:PS:UG:UQ	0|1:4.06:53824:0/1:34.97
ptg000002l	54482	.	T	G	31.57	PASS	DP=9;AC=5,3;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=36;MQ10=0.47;MQ20=0.42;MQ30=0.25;MQ40=0.25;MQ50=0.19;PH=31.57,3.01,3.01,129.59;SC=GGCTGTGCCCTCGGCCTATTT;	GT:GQ:PS:UG:UQ	0/1:31.57:.:0/1:31.57
ptg000002l	56222	.	T	G	11.01	PASS	DP=38;AC=30,5;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=64;MQ10=0.72;MQ20=0.69;MQ30=0.59;MQ40=0.58;MQ50=0.55;PH=11.01,3.37,3.37,500.00;SC=AGCCCACCCGTTTTTGTGGCC;	GT:GQ:PS:UG:UQ	0/1:11.01:.:0/1:11.01
ptg000002l	58436	.	T	G	8.22	PASS	DP=19;AC=13,3;AM=1;MC=0;MF=0.000;MB=0.000;AQ=15.18;GM=1;DA=31;MQ10=0.87;MQ20=0.77;MQ30=0.61;MQ40=0.48;MQ50=0.19;PH=8.22,3.72,3.72,347.26;SC=CGCCCCGGCCTTCGGCCGGTT;	GT:GQ:PS:UG:UQ	0/1:8.22:.:0/1:8.22
ptg000002l	58574	.	T	G	61.75	PASS	DP=20;AC=13,5;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=46;MQ10=0.85;MQ20=0.72;MQ30=0.43;MQ40=0.22;MQ50=0.15;PH=61.75,3.01,3.01,340.53;SC=AGCCCACCCGTTTTTGTGGCT;	GT:GQ:PS:UG:UQ	0/1:61.75:.:0/1:61.75
ptg000002l	59095	.	G	C	13.78	PASS	DP=27;AC=20,4;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=39;MQ10=0.79;MQ20=0.69;MQ30=0.69;MQ40=0.64;MQ50=0.59;PH=13.78,3.20,3.20,500.00;SC=CTGCCCCACCGCCCAAGGCTA;	GT:GQ:PS:UG:UQ	0/1:13.78:.:0/1:13.78
ptg000002l	61230	.	T	G	19.65	PASS	DP=22;AC=18,4;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=33;MQ10=0.79;MQ20=0.79;MQ30=0.67;MQ40=0.58;MQ50=0.55;PH=19.65,3.06,3.06,479.18;SC=TCTCACGCCATTCCGAGTCCG;	GT:GQ:PS:UG:UQ	0/1:19.65:.:0/1:19.65
ptg000002l	67804	.	T	C	22.63	PASS	DP=23;AC=17,4;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=26;MQ10=0.96;MQ20=0.92;MQ30=0.88;MQ40=0.88;MQ50=0.81;PH=22.63,3.03,3.03,452.02;SC=GCGGCCTTTTTCCGCTGGACA;	GT:GQ:PS:UG:UQ	0/1:22.63:.:0/1:22.63
ptg000002l	70727	.	T	G	31.57	PASS	DP=8;AC=5,3;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=20;MQ10=0.55;MQ20=0.55;MQ30=0.40;MQ40=0.40;MQ50=0.40;PH=31.57,3.01,3.01,129.59;SC=CGCCCCGGCCTTCGGGCGGTT;	GT:GQ:PS:UG:UQ	0/1:31.57:.:0/1:31.57
ptg000002l	73944	.	T	G	5.13	PASS	DP=21;AC=14,3;AM=0;MC=0;MF=0.000;MB=0.000;AQ=29.59;GM=1;DA=43;MQ10=0.65;MQ20=0.63;MQ30=0.49;MQ40=0.42;MQ50=0.30;PH=5.13,4.60,4.60,370.49;SC=ATCCCACCCGTTTTTGTGGCC;	GT:GQ:PS:UG:UQ	0/1:5.13:.:0/1:5.13
ptg000002l	91485	.	T	G	13.35	PASS	DP=14;AC=11,3;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.10;GM=1;DA=22;MQ10=0.77;MQ20=0.73;MQ30=0.64;MQ40=0.41;MQ50=0.36;PH=13.35,3.22,3.22,292.51;SC=AGCCCACCCGTTTTTGTGGCC;	GT:GQ:PS:UG:UQ	0/1:13.35:.:0/1:13.35
ptg000002l	95466	.	A	C	31.63	PASS	DP=21;AC=14,4;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=36;MQ10=0.69;MQ20=0.69;MQ30=0.58;MQ40=0.53;MQ50=0.47;PH=31.63,3.01,3.01,370.66;SC=CCCACCCCCCAAGGCTATAGC;	GT:GQ:PS:UG:UQ	0/1:31.63:.:0/1:31.63
ptg000002l	96079	.	T	G	10.95	PASS	DP=26;AC=21,4;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=42;MQ10=0.83;MQ20=0.69;MQ30=0.62;MQ40=0.60;MQ50=0.48;PH=10.95,3.37,3.37,500.00;SC=GTTCGGGCGGTTATTTTTGGG;	GT:GQ:PS:UG:UQ	0/1:10.95:.:0/1:10.95
ptg000002l	96529	.	T	G	22.55	PASS	DP=11;AC=8,3;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=33;MQ10=0.64;MQ20=0.55;MQ30=0.33;MQ40=0.21;MQ50=0.18;PH=22.55,3.03,3.03,210.97;SC=TCCGGCGAACTAAGTTGGCCA;	GT:GQ:PS:UG:UQ	0/1:22.55:.:0/1:22.55
ptg000002l	99173	.	T	G	19.43	PASS	DP=17;AC=14,3;AM=0;MC=1;MF=0.059;MB=0.031;AQ=30.13;GM=1;DA=29;MQ10=1.00;MQ20=0.90;MQ30=0.59;MQ40=0.48;MQ50=0.45;PH=19.43,0.05,352.54,388.61;SC=CACCCACCCGTTTTTGTGGGC;	GT:GQ:PS:UG:UQ	0|1:19.43:99173:0/1:5.80
ptg000002l	99216	.	T	G	25.44	PASS	DP=16;AC=12,3;AM=0;MC=0;MF=0.000;MB=0.031;AQ=30.13;GM=1;DA=29;MQ10=0.90;MQ20=0.83;MQ30=0.55;MQ40=0.48;MQ50=0.45;PH=25.44,0.01,352.50,334.34;SC=CGCCGCGGCCTTCGGGCGGGT;	GT:GQ:PS:UG:UQ	0|1:25.44:99173:0/1:10.89
ptg000002l	99538	.	T	G	98.25	PASS	DP=28;AC=18,7;AM=0;MC=0;MF=0.000;MB=0.000;AQ=29.97;GM=1;DA=37;MQ10=0.97;MQ20=0.92;MQ30=0.76;MQ40=0.68;MQ50=0.51;PH=98.25,3.01,3.01,469.80;SC=CACCCACCCGTTTTTGTGGGC;	GT:GQ:PS:UG:UQ	0/1:98.25:.:0/1:98.25
ptg000002l	101535	.	T	G	46.69	PASS	DP=23;AC=18,5;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=37;MQ10=0.76;MQ20=0.73;MQ30=0.62;MQ40=0.57;MQ50=0.32;PH=46.69,3.01,3.01,476.12;SC=CACCCACCCGTTTTTGTGGGC;	GT:GQ:PS:UG:UQ	0/1:46.69:.:0/1:46.68
ptg000002l	101897	.	A	C	13.78	PASS	DP=24;AC=20,4;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=36;MQ10=0.78;MQ20=0.78;MQ30=0.67;MQ40=0.64;MQ50=0.58;PH=13.78,3.20,3.20,500.00;SC=TAGCCCACCCATTTTTGTGGG;	GT:GQ:PS:UG:UQ	0/1:13.78:.:0/1:13.78
ptg000002l	123915	.	T	G	22.62	PASS	DP=24;AC=17,4;AM=1;MC=0;MF=0.000;MB=0.000;AQ=16.26;GM=1;DA=29;MQ10=0.93;MQ20=0.90;MQ30=0.83;MQ40=0.72;MQ50=0.69;PH=22.62,3.03,3.03,452.03;SC=AGCCCTCCCGTTTTTGTGGTC;	GT:GQ:PS:UG:UQ	0/1:22.62:.:0/1:22.62
ptg000003l	34038	.	G	T	11.01	PASS	DP=36;AC=30,5;AM=0;MC=0;MF=0.000;MB=0.000;AQ=30.13;GM=1;DA=36;MQ10=1.00;MQ20=1.00;MQ30=1.00;MQ40=1.00;MQ50=1.00;PH=11.01,3.37,3.37,500.00;SC=GTTTATTTTTGGGCGAAGTTC;	GT:GQ:PS:UG:UQ	0/1:11.01:.:0/1:11.01
ptg000003l	34930	.	A	C	5.87	PASS	DP=31;AC=23,4;AM=4;MC=0;MF=0.000;MB=0.000;AQ=11.85;GM=1;DA=32;MQ10=0.97;MQ20=0.97;MQ30=0.97;MQ40=0.94;MQ50=0.94;PH=5.87,4.31,4.31,500.00;SC=CAAAAAAACGATTGGGCTATA;	GT:GQ:PS:UG:UQ	0/1:5.87:.:0/1:5.87

Any help would be really great.
Best

**Comment by Mondlii** [comment]
Hi, Just wondering if you were able to get any help or find a work around for this issue? 

Thanks for your response 
Regards

**Comment by ptrebert** [comment]
I just took a brief look, and the error...
```
[E::vcf_parse_format] Invalid character '.' in 'GQ' FORMAT field at ptg000003l:13085
```
...indicates that the VCF file is not format compliant - quote from the VCF v4.2 spec:
```
GQ : conditional genotype quality, encoded as a phred quality −10log10 p(genotype call is wrong, conditioned
on the site’s being variant) (Integer)
```
One possible fix is to make one pass over the file and round the GQ field to integers before continuing the downstream analysis.
