### ISSUE TITLE
UnboundLocalError: local variable 'merged_reads' referenced before assignment

### ISSUE THREAD

**Issue by jainy** [whatshap/whatshap#333]
Hi, 

I get the error below when I use --merge-reads option

This is the command line I used: `whatshap phase             --output deepvariant.phased.vcf.gz             --reference human_g1k_v37_modified.fasta             --tag=PS             --ignore-read-groups             --merge-reads             deepvariant.vcf.gz aligned.bam`

This is WhatsHap 1.1 running under Python 3.9.6

Working on 1 samples from 1 family
======== Working on chromosome '6'
---- Processing individual SQ6687
Using maximum coverage per sample of 15X
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 0
Reading alignments and detecting alleles ...
Found 0 reads covering 0 variants
Kept 0 reads that cover at least two variants each
Merging 0 reads with error rate 0.15, maximum error rate 0.25, positive threshold 1000000 and negative threshold 1000 ...
Traceback (most recent call last):
  File "/home/thomas/miniconda3/envs/snakemake/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/thomas/miniconda3/envs/snakemake/lib/python3.9/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home/thomas/miniconda3/envs/snakemake/lib/python3.9/site-packages/whatshap/cli/phase.py", line 1107, in main
    run_whatshap(**vars(args))
  File "/home/thomas/miniconda3/envs/snakemake/lib/python3.9/site-packages/whatshap/cli/phase.py", line 469, in run_whatshap
    merged_reads = read_merger.merge(readset)
  File "/home/thomas/miniconda3/envs/snakemake/lib/python3.9/site-packages/whatshap/merge.py", line 236, in merge
    "... after merging: merged %d reads into %d reads", len(readset), len(merged_reads)
UnboundLocalError: local variable 'merged_reads' referenced before assignment

**Comment by marcelm** [comment]
Hi, this has been reported before in issue #208, and unfortunately we haven’t found a solution, yet.

I recommend that you do not use the `--merge-reads` option for the moment.

Closing this now because #208 exists. Please click on 'subscribe' over there to be notified when we fix it!
