### ISSUE TITLE
whatshap split - Gzipped list not working

### ISSUE THREAD

**Issue by pontushojer** [whatshap/whatshap#367]
Running `whatshap split` using a gzipped list results in the following error. 

```
Traceback (most recent call last):
  File "/Users/pontus.hojer/miniconda3/envs/blr/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/Users/pontus.hojer/miniconda3/envs/blr/lib/python3.6/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/Users/pontus.hojer/miniconda3/envs/blr/lib/python3.6/site-packages/whatshap/cli/split.py", line 490, in main
    run_split(**vars(args))
  File "/Users/pontus.hojer/miniconda3/envs/blr/lib/python3.6/site-packages/whatshap/cli/split.py", line 364, in run_split
    list_file, stack
  File "/Users/pontus.hojer/miniconda3/envs/blr/lib/python3.6/site-packages/whatshap/cli/split.py", line 241, in check_haplotag_list_information
    haplo_list.seek(0)
AttributeError: 'PipedIGzipReader' object has no attribute 'seek'
```

I did some digging and it seems like the minimum `xopen` version should be updated to 1.4.0 from 1.2.0 as this is where `seek` was added to `PipedIGzipReader` 
(this commit https://github.com/pycompression/xopen/commit/d95ef08dd28b3ec3e785bf25724fbee9ad35b11a).

whathap: 1.3
python: 3.6.13

**Comment by marcelm** [comment]
Thanks for reporting!

The `seek()` method added in that commit only works on Windows, but will raise `UnsupportedOperation` on Unix, so bumping the required xopen version will unfortunately not help.

I think opening the file without using an external process (that is, not using a `PipedIGzipReader`) should make it work. Can you please try to manually edit `split.py` and change (around line 238)
```
haplo_list = exit_stack.enter_context(xopen(haplotag_list))
```
to
```
haplo_list = exit_stack.enter_context(xopen(haplotag_list, threads=0))
```
and see if that makes a difference?

**Comment by pontushojer** [comment]
@marcelm That worked perfectly, I took the liberty of making a PR with your fix.
