### ISSUE TITLE
whatshap split TypeError

### ISSUE THREAD

**Issue by BenjaminJPerry** [whatshap/whatshap#371]
I am trying to split fastq reads using phasing information and get this error message:

```
iramohio-01$ singularity exec /home/perrybe/containers/whatshap/whatshap_1.4--py38h4a32c8e_0.sif whatshap split /dataset/Bee_csd_Amplicon_Sequencing/active/220304_Flongle_guppy_v601_r941_450bps_sup/flongle.barcode04.fastq.gz /dataset/Bee_csd_Amplicon_Sequencing//active/namplicon/haplotag.read.list.txt --output-h1 /dataset/Bee_csd_Amplicon_Sequencing/active/namplicon/H1.test.fastq --output-h2 /dataset/Bee_csd_Amplicon_Sequencing/active/namplicon/H2.test.fastq
Total number of reads in haplotag list: 3899
Total number of haplo-tagged reads: 3897
Total number of untagged reads: 2
Traceback (most recent call last):
  File "/usr/local/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/usr/local/lib/python3.8/site-packages/whatshap/cli/split.py", line 490, in main
    run_split(**vars(args))
  File "/usr/local/lib/python3.8/site-packages/whatshap/cli/split.py", line 398, in run_split
    input_reader, input_iterator, output_writers = initialize_io_files(
  File "/usr/local/lib/python3.8/site-packages/whatshap/cli/split.py", line 319, in initialize_io_files
    open_handle = exit_stack.enter_context(xopen(outfile, "w"))
  File "/usr/local/lib/python3.8/site-packages/xopen/__init__.py", line 1056, in xopen
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I have reproduced this error message using a conda installation of whatshap  as well:

```
(/home/perrybe/conda-envs/whatshap) iramohio-01$ whatshap split /dataset/Bee_csd_Amplicon_Sequencing/active/220304_Flongle_guppy_v601_r941_450bps_sup/flongle.barcode04.fastq.gz /dataset/Bee_csd_Amplicon_Sequencing//active/namplicon/haplotag.read.list.txt --output-h1 /dataset/Bee_csd_Amplicon_Sequencing/active/namplicon/H1.test.fastq --output-h2 /dataset/Bee_csd_Amplicon_Sequencing/active/namplicon/H2.test.fastq
Total number of reads in haplotag list: 3899
Total number of haplo-tagged reads: 3897
Total number of untagged reads: 2
Traceback (most recent call last):
  File "/home/perrybe/conda-envs/whatshap/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/perrybe/conda-envs/whatshap/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/perrybe/conda-envs/whatshap/lib/python3.9/site-packages/whatshap/cli/split.py", line 490, in main
    run_split(**vars(args))
  File "/home/perrybe/conda-envs/whatshap/lib/python3.9/site-packages/whatshap/cli/split.py", line 398, in run_split
    input_reader, input_iterator, output_writers = initialize_io_files(
  File "/home/perrybe/conda-envs/whatshap/lib/python3.9/site-packages/whatshap/cli/split.py", line 319, in initialize_io_files
    open_handle = exit_stack.enter_context(xopen(outfile, "w"))
  File "/home/perrybe/conda-envs/whatshap/lib/python3.9/site-packages/xopen/__init__.py", line 1056, in xopen
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

with conda env install is: 

whatshap                  1.4              py39hc16433a_0    bioconda

and,

```
(/home/perrybe/conda-envs/whatshap) iramohio-01$ python -V
Python 3.9.12
```

**Comment by marcelm** [comment]
Thanks for reporting! I get the feeling that splitting FASTQ input never worked. I’ve attempted to fix this and added a couple of tests to make sure that this continues to work.

Can you try [to run the development version](https://whatshap.readthedocs.io/en/latest/installation.html#installing-an-unreleased-development-version)?

**Comment by BenjaminJPerry** [comment]
Hello, thank you for your quick response :)

I ran the dev version (linked above) as follows and split works 🥇 from fastq or bam format READS input; however, the gz compression for output does not appear to work when READS input is .bam

```
(/home/perrybe/conda-envs/whatshap-tmp) iramohio-01$ whatshap --version
1.5.dev8+g3555cc3
```
```
(/home/perrybe/conda-envs/whatshap-tmp) iramohio-01$ whatshap split 4_filt/barcode04.chop.primer.scrubb.filt.fastq.gz haplotag.read.list.txt --output-h1 H1.test.fastq --output-h2 H2.test.fastq
Total number of reads in haplotag list: 3899
Total number of haplo-tagged reads: 3897
Total number of untagged reads: 2

== SUMMARY ==
Total reads processed: 4010
Number of output reads "untagged": 0
Number of output reads haplotype 1: 2180
Number of output reads haplotype 2: 1717
Number of unknown (dropped) reads: 0
Number of skipped reads (per user request): 113
Time for processing haplotag list: 0.003 sec
Time for total initial setup: 0.006 sec
Time for iterating input reads: 0.035 sec
Total run time: 0.054 sec
```
```
(/home/perrybe/conda-envs/whatshap-tmp) iramohio-01$ whatshap split 4_filt/barcode04.chop.primer.scrubb.filt.fastq.gz haplotag.read.list.txt --output-h1 H1.test.fastq.gz --output-h2 H2.test.fastq.gz
Total number of reads in haplotag list: 3899
Total number of haplo-tagged reads: 3897
Total number of untagged reads: 2

== SUMMARY ==
Total reads processed: 4010
Number of output reads "untagged": 0
Number of output reads haplotype 1: 2180
Number of output reads haplotype 2: 1717
Number of unknown (dropped) reads: 0
Number of skipped reads (per user request): 113
Time for processing haplotag list: 0.003 sec
Time for total initial setup: 0.013 sec
Time for iterating input reads: 0.064 sec
Total run time: 0.096 sec
```
```
(/home/perrybe/conda-envs/whatshap-tmp) iramohio-01$ whatshap split haplotag.test.bam haplotag.read.list.txt --output-h1 H1.test.bam.fastq --output-h2 H2.test.bam.fastq
Total number of reads in haplotag list: 3899
Total number of haplo-tagged reads: 3897
Total number of untagged reads: 2

== SUMMARY ==
Total reads processed: 3899
Number of output reads "untagged": 0
Number of output reads haplotype 1: 2180
Number of output reads haplotype 2: 1717
Number of unknown (dropped) reads: 0
Number of skipped reads (per user request): 2
Time for processing haplotag list: 0.003 sec
Time for total initial setup: 0.007 sec
Time for iterating input reads: 0.161 sec
Total run time: 0.177 sec
```
```
(/home/perrybe/conda-envs/whatshap-tmp) iramohio-01$ whatshap split haplotag.test.bam haplotag.read.list.txt --output-h1 H1.test.bam.fastq.gz --output-h2 H2.test.bam.fastq.gz
Total number of reads in haplotag list: 3899
Total number of haplo-tagged reads: 3897
Total number of untagged reads: 2

== SUMMARY ==
Total reads processed: 3899
Number of output reads "untagged": 0
Number of output reads haplotype 1: 2180
Number of output reads haplotype 2: 1717
Number of unknown (dropped) reads: 0
Number of skipped reads (per user request): 2
Time for processing haplotag list: 0.003 sec
Time for total initial setup: 0.006 sec
Time for iterating input reads: 0.146 sec
Total run time: 0.16 sec
```
```
(/home/perrybe/conda-envs/whatshap-tmp) iramohio-01$ ls -l | grep "H"
-rw-rw-r--  1 perrybe bioinformatics_users  886562 May 25 11:44 H1.test.bam.fastq <---
-rw-rw-r--  1 perrybe bioinformatics_users  886562 May 25 11:44 H1.test.bam.fastq.gz <---
-rw-rw-r--  1 perrybe bioinformatics_users 2117688 May 25 11:43 H1.test.fastq
-rw-rw-r--  1 perrybe bioinformatics_users  810921 May 25 11:43 H1.test.fastq.gz
-rw-rw-r--  1 perrybe bioinformatics_users  699572 May 25 11:44 H2.test.bam.fastq <---
-rw-rw-r--  1 perrybe bioinformatics_users  699572 May 25 11:44 H2.test.bam.fastq.gz <---
-rw-rw-r--  1 perrybe bioinformatics_users 1622985 May 25 11:43 H2.test.fastq
-rw-rw-r--  1 perrybe bioinformatics_users  625000 May 25 11:43 H2.test.fastq.gz
```

This is a very value utility. Is there going to be a version for splitting phasing beyond diploids? As in split READS with LIST into all uniq haplotypes?

Thanks!

**Comment by BenjaminJPerry** [comment]
I realise now the outputs .bam when the inputs are .bam! My mistake!

Works great! Thanks 👍

**Comment by marcelm** [comment]
> I realise now the outputs .bam when the inputs are .bam! 

I noticed `whatshap split` isn’t documented too well, so I added a short section to the documentation where I point out that the output is in the same format as the input: https://whatshap.readthedocs.io/en/latest/guide.html#whatshap-split

> Is there going to be a version for splitting phasing beyond diploids? As in split READS with LIST into all uniq haplotypes?

Can you please open a separate feature request for that?
