### ISSUE TITLE
Mismatch between total number of reads and known reads: 

### ISSUE THREAD

**Issue by bluessherpa** [whatshap/whatshap#378]
Howdy!

I have an issue with the whatshap about not having the same number of reads.  Here is the error.  

[M::main] CMD: minimap2 -a -x map-ont -t 30 --secondary=no /project/hwwgru_mhk/jpf/prtus6/pt_race_1_HAP1_contigs_filt_medakacon_hypo_rn_v30.fasta /project/hwwgru_mhk/jpf/prtus6/prtus6_gdnaall3_hiac_pchop.fastq
[M::main] Real time: 1579.288 sec; CPU: 30870.547 sec; Peak RSS: 18.151 GB
[bam_sort_core] merging from 12 files and 2 in-memory blocks...
[W::hts_idx_load3] The index file is older than the data file: /project/hwwgru_mhk/jpf/prtus6/pt_race_1_HAP1_contigs_filt_medakacon_hypo_rn_v30_medaka.qual20.vcf.gz.tbi
Found 1 sample(s) in input VCF
Found 0 sample(s) in BAM file
Reading alignments on chromosome chr_1_h1 and detecting alleles ...
Found 71913 reads covering 29224 variants
Reading alignments on chromosome chr_2_h1 and detecting alleles ...
Found 69455 reads covering 21923 variants
Reading alignments on chromosome chr_3_h1 and detecting alleles ...
Found 53612 reads covering 22695 variants
Reading alignments on chromosome chr_4_h1 and detecting alleles ...
Found 66238 reads covering 26724 variants
Reading alignments on chromosome chr_5_h1 and detecting alleles ...
Found 64486 reads covering 27883 variants
Reading alignments on chromosome chr_6_h1 and detecting alleles ...
Found 61518 reads covering 21328 variants
Reading alignments on chromosome chr_7_h1 and detecting alleles ...
Found 64461 reads covering 31285 variants
Reading alignments on chromosome chr_8_h1 and detecting alleles ...
Found 61253 reads covering 26351 variants
Reading alignments on chromosome chr_9_h1 and detecting alleles ...
Found 55883 reads covering 18563 variants
Reading alignments on chromosome chr_10_h1 and detecting alleles ...
Found 58506 reads covering 29573 variants
Reading alignments on chromosome chr_11_h1 and detecting alleles ...
Found 51643 reads covering 23446 variants
Reading alignments on chromosome chr_12_h1 and detecting alleles ...
Found 52017 reads covering 30253 variants
Reading alignments on chromosome chr_13_h1 and detecting alleles ...
Found 37089 reads covering 11563 variants
Reading alignments on chromosome chr_14_h1 and detecting alleles ...
Found 37476 reads covering 9688 variants
Reading alignments on chromosome chr_15_h1 and detecting alleles ...
Found 37201 reads covering 14167 variants
Reading alignments on chromosome chr_16_h1 and detecting alleles ...
Found 37775 reads covering 16278 variants
Reading alignments on chromosome chr_17_h1 and detecting alleles ...
Found 31001 reads covering 12490 variants
Reading alignments on chromosome chr_18_h1 and detecting alleles ...
Found 34462 reads covering 15610 variants

== SUMMARY ==
Total alignments processed:                   1983932
Alignments that could be tagged:               948088
Alignments spanning multiple phase sets:            0
Finished in 2413.9 s
Total number of reads in haplotag list: 1318371
Total number of haplo-tagged reads: 933901
Total number of untagged reads: 384470
Traceback (most recent call last):
  File "/home/john.fellers/.local/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/home/john.fellers/.local/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/john.fellers/.local/lib/python3.9/site-packages/whatshap/cli/split.py", line 490, in main
    run_split(**vars(args))
  File "/home/john.fellers/.local/lib/python3.9/site-packages/whatshap/cli/split.py", line 381, in run_split
    readname_to_haplotype, known_reads = process_haplotag_list_file(
  File "/home/john.fellers/.local/lib/python3.9/site-packages/whatshap/cli/split.py", line 158, in process_haplotag_list_file
    assert (
AssertionError: Mismatch between total number of reads and known reads: 1318371 vs 1300772

I am using the same slurm with other ONT read  files created in the same manner and they seem to work.  But with this one fungal race, I get this error and it fails.  Any ideas on how to fix?

Thanks.
John

Whatshap version 1.4
Python 3.9.2
Pip

Command slurm
for i in ${READS[@]} ; do
BAM_FILE=${VCF_1%%.vcf}.bam ; \
minimap2 -a -x map-ont -t 30 $GENOME $i --secondary=no | samtools view -hF 256 - | samtools sort -@ 2 -m 2G -o $BAM_FILE -T reads.tmp && \
samtools index $BAM_FILE ;
done

whatshap haplotag \
--ignore-read-groups \
--output-haplotag-list $(basename ${i%%.fastq})_readlist.txt \
--reference $GENOME \
-o $(basename ${i%%.fastq})_medaka.bam \
${VCF_1} $BAM_FILE && \

whatshap split \
--discard-unknown-reads \
--add-untagged \
--output-untagged ${GENOME%%.fasta}_$(basename ${i%%.fastq})_untagged.fastq \
--output-h1 ${GENOME%%.fasta}_$(basename ${i%%.fastq})_H1.fastq \
--output-h2 ${GENOME%%.fasta}_$(basename ${i%%.fastq})_H2.fastq \
$i \
$(basename ${i%%.fastq})_readlist.txt \

**Comment by marcelm** [comment]
Thanks for reporting. This error occurs only when using `--discard-unknown-reads`, so you could omit that option for the moment.

I’ll investigate when I have more time. At the moment, I’m not even sure what `--discard-unknown-reads` is intended to do.

**Comment by bluessherpa** [comment]
Thanks very much!!

**Comment by marcelm** [comment]
Hi, can you check whether you have duplicated read names in your `_readlist.txt`? You can use this command:
```
cut -f1 your-readlist.txt | sort | uniq -c | awk '$1>1'
```
If there is any output, then you have duplicate read names.

If there are any, I don’t quite know, yet, where these come from, yet. My first guess is that these are supplementary alignments, but `whatshap haplotag` should be able to deal with them (and they should not be written to the haplotag list file), but perhaps something is buggy.

You could try filtering out supplementary alignments by replacing your `samtools view -hF 256` with `samtools view -hF 0x900`. 

If you can share the data (possibly a smaller subset that still exhibits the problem), I could try to reproduce the problem myself.

**Comment by marcelm** [comment]
I’ll leave this issue open for now, but marked it as "feedback needed" since I would need a dataset that exhibits the problem in order to reproduce it myself.

**Comment by DHmeduni** [comment]
Hi,
I've been able to reproduce the problem Whatshap v2.8. Any interest in the dataset?

Total number of reads in haplotag list: 526
Total number of haplo-tagged reads: 353
Total number of untagged reads: 173
Traceback (most recent call last):
  File "/opt/conda/envs/whatshap-env/bin/whatshap", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/whatshap-env/lib/python3.12/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/opt/conda/envs/whatshap-env/lib/python3.12/site-packages/whatshap/cli/split.py", line 476, in main
    run_split(**vars(args))
  File "/opt/conda/envs/whatshap-env/lib/python3.12/site-packages/whatshap/cli/split.py", line 374, in run_split
    readname_to_haplotype, known_reads = process_haplotag_list_file(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/whatshap-env/lib/python3.12/site-packages/whatshap/cli/split.py", line 171, in process_haplotag_list_file
    assert total_reads == num_known_reads, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Total number of reads is not equal to number of known reads: 526 != 456


Output from whatshap phase:

Found 1 sample(s) in input VCF
Found 0 sample(s) in BAM file
Number of supplementary alignments: 46
WARNING: Read name '748a777d-6ffc-46fc-af2a-192b0ad07772' has more than two primary alignments.
WARNING: Read name 'ae1ee0c6-1c37-4a81-b237-5aa38ab2e76e' has more than two primary alignments.
WARNING: Read name 'ed744856-5fd4-41a5-a23a-4ad4007b107d' has more than two primary alignments.
Number of non-singleton groups: 21
Skipped 4 groups
Found 361 reads covering 423 variants

== SUMMARY ==
Total alignments processed:                       549
Alignments that could be tagged:                  389
Alignments spanning multiple phase sets:            0
Finished in 1.5 s
