### ISSUE TITLE
whathap genotype error

### ISSUE THREAD

**Issue by ziczhang** [whatshap/whatshap#380]
Hi, I meet the error below when I was running whatshap genotype.

```
======== Writing VCF
Traceback (most recent call last):
  File "/home/zicong_zhang/miniconda3/envs/whatshap/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/zicong_zhang/miniconda3/envs/whatshap/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/zicong_zhang/miniconda3/envs/whatshap/lib/python3.9/site-packages/whatshap/cli/genotype.py", line 489, in main
    run_genotype(**vars(args))
  File "/home/zicong_zhang/miniconda3/envs/whatshap/lib/python3.9/site-packages/whatshap/cli/genotype.py", line 370, in run_genotype
    vcf_writer.write_genotypes(chromosome, variant_table, indels)
  File "/home/zicong_zhang/miniconda3/envs/whatshap/lib/python3.9/site-packages/whatshap/vcf.py", line 1167, in write_genotypes
    geno_q = sum(geno_l[i] for i in range(n_genotypes) if i != geno_index)
  File "/home/zicong_zhang/miniconda3/envs/whatshap/lib/python3.9/site-packages/whatshap/vcf.py", line 1167, in <genexpr>
    geno_q = sum(geno_l[i] for i in range(n_genotypes) if i != geno_index)
IndexError: list index out of range
```

- WhatsHap and Python version (`python -V` and `whatshap --version`)
Python 3.9.13, Whatshap 1.4
- How you installed the tool (conda, pip)
conda
- Which command-line parameters you used
The whatshap command I used was
`whatshap genotype --indels --ignore-read-groups --reference=$REF -o $OUTPUT $INPUT_VCF $BAM
`

I think the output was stopped when processing this mutation.
`chr1    600968  .       A       ATGTGGAGTCTGGGAGGATGCGGGGTCCGGGACGATGCCCGGTCTGG,ATGTGGAGTCTGGGAGGATGCGGGGTCCGGGACGATGCCTGGTCTGG 39.60   PASS    .       GT:GQ:DP:AD:VAF:PL      1
/2:32:63:0,15,18:0.238095,0.285714:39,46,39,46,0,34`

Any suggestions please?

Best,
Zicong

**Comment by sashulkaSh** [comment]
I had the same problem when the column already had information about the genotype (1/0 and so on 0/0)

**Comment by Lies-VO** [comment]
I had the same problem with an RNA vcf and bam file, but they did not already have GT information.
The vcf file was generated with Strelka2, the bam file with STAR.
