### ISSUE TITLE
TypeError: __new__() missing 1 required positional argument: 'type_code'

### ISSUE THREAD

**Issue by michaeljmetzger** [whatshap/whatshap#403]
We are having an error running WhatsHap. It looks like ther is an error thrown in the parsing of the vcf files--we have tried generating vcf files with both Genious and FreeBayes with the same error.

The command is:
whatshap phase -o SM6H-aT_02_phased.vcf --distrust-genotypes  --ignore-read-groups --reference=SM6H-aT_02.fasta SM6H-aT_02-ed.vcf SM6H-aT_02.bam

The output we get is:
This is WhatsHap 0.18 running under Python 3.6.13
Traceback (most recent call last):
  File "/home/jsevigny/.conda/envs/WhatsHap/bin/whatshap", line 12, in <module>
    sys.exit(main())
  File "/home/jsevigny/.conda/envs/WhatsHap/lib/python3.6/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home/jsevigny/.conda/envs/WhatsHap/lib/python3.6/site-packages/whatshap/phase.py", line 1114, in main
    run_whatshap(**vars(args))
  File "/home/jsevigny/.conda/envs/WhatsHap/lib/python3.6/site-packages/whatshap/phase.py", line 580, in run_whatshap
    out_file=output, tag=tag)
  File "/home/jsevigny/.conda/envs/WhatsHap/lib/python3.6/site-packages/whatshap/vcf.py", line 493, in __init__
    fmt = vcf.parser._Format(id=tag, num=1, type='Integer', desc=desc)
TypeError: __new__() missing 1 required positional argument: 'type_code' 

It looks like this is related to the vcf header, as the only citation we can find of "type_code" is a part of this site describing bio.vcf (https://docs.seq-lang.org/stdlib/bio/vcf.html). It even mentiones the "__new__" thing, although I still do not know how this could be throwing an error:
classbio.vcf.BCFHeaderMetaData
Properties:
type_code
Magic methods:
__new__(bcf_hdr: Ptr[_bcf_hdr_t], _type_code: int)
__len__()
__iter__()

Does anyone have any experience with this error or how it can be avoided?

I am also pasting below an example of the vcf file that causes this error:
##fileformat=VCFv4.2
##fileDate=20221004
##source=GeneiousPrimeV2022.2.2
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth at this position for this sample">
##INFO=<ID=VF,Number=1,Type=Float,Description="Variant Frequency">
##FORMAT=<ID=AO,Number=A,Type=Integer,Description="Variant Raw Frequency">
##INFO=<ID=SB,Number=1,Type=Float,Description="Strand bias at this position">
##INFO=<ID=SB50,Number=1,Type=Float,Description="Strand-bias >50% P-value">
##INFO=<ID=SB65,Number=1,Type=Float,Description="Strand-bias >65% P-value">
##INFO=<ID=TYPE,Number=1,Type=String,Description="Polymorphism Type">
##INFO=<ID=AVQUAL,Number=1,Type=Float,Description="Average Quality">
##INFO=<ID=RF,Number=1,Type=Float,Description="Reference Frequency">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Variants:_7J8TJB_2_2
SM6H-aT_02__circular=0.00	1	.	C	A	100.00	.	NS=1;VF=1.000;SB=1.000;SB50=0.063;SB65=0.23;TYPE=SNP(transversion);AVQUAL=21	DP:AO	5:5
SM6H-aT_02__circular=0.00	250	.	A	T	107.45	.	NS=1;RF=0.978;VF=0.022;SB=0.857;SB50=0.12;SB65=0.47;TYPE=SNP(transversion);AVQUAL=36	DP:AO	318:7
SM6H-aT_02__circular=0.00	298	.	T	TAC	1708.24	.	NS=1;VF=0.272;SB=0.793;SB50=9.0E-8;SB65=0.0073;TYPE=Insertion;AVQUAL=32	DP:AO	301:82
SM6H-aT_02__circular=0.00	329	.	G	A	1593.77	.	NS=1;RF=0.691;VF=0.279;SB=0.789;SB50=3.9E-7;SB65=0.012;TYPE=SNP(transition);AVQUAL=30	DP:AO	272:76
SM6H-aT_02__circular=0.00	354	.	A	C	2811.19	.	NS=1;RF=0.646;VF=0.351;SB=0.620;SB50=0.021;SB65=1.0;TYPE=SNP(transversion);AVQUAL=36	DP:AO	285:100
SM6H-aT_02__circular=0.00	358	.	C	T	2643.10	.	NS=1;RF=0.652;VF=0.341;SB=0.612;SB50=0.033;SB65=1.0;TYPE=SNP(transition);AVQUAL=35	DP:AO	287:98
SM6H-aT_02__circular=0.00	381	.	T	C	2296.99	.	NS=1;RF=0.652;VF=0.341;SB=0.533;SB50=0.60;SB65=1.0;TYPE=SNP(transition);AVQUAL=33	DP:AO	270:92
SM6H-aT_02__circular=0.00	384	.	C	A	2561.74	.	NS=1;RF=0.640;VF=0.353;SB=0.582;SB50=0.13;SB65=1.0;TYPE=SNP(transversion);AVQUAL=34	DP:AO	278:98
SM6H-aT_02__circular=0.00	425	.	T	C	3200.00	.	NS=1;RF=0.589;VF=0.411;SB=0.761;SB50=1.0E-9;SB65=0.0075;TYPE=SNP(transition);AVQUAL=31	DP:AO	326:134
SM6H-aT_02__circular=0.00	446	.	T	A	3200.00	.	NS=1;RF=0.553;VF=0.447;SB=0.762;SB50=1.4E-10;SB65=0.0046;TYPE=SNP(transversion);AVQUAL=30	DP:AO	329:147
SM6H-aT_02__circular=0.00	465	.	T	C	3200.00	.	NS=1;RF=0.555;VF=0.445;SB=0.808;SB50=3.0E-16;SB65=0.000011;TYPE=SNP(transition);AVQUAL=30	DP:AO	375:167
SM6H-aT_02__circular=0.00	520	.	A	C	240.00	.	NS=1;RF=0.969;VF=0.031;SB=0.923;SB50=0.0034;SB65=0.059;TYPE=SNP(transversion);AVQUAL=38	DP:AO	414:13

Thanks,
Michael

**Comment by marcelm** [comment]
Hi, can you try using a more recent WhatsHap version? The current version is 1.6. The VCF parsing code was overhauled completely in version 1.0.

**Comment by michaeljmetzger** [comment]
Aha! We just installed it last week using the conda installation commands recommended on the website so I never thought to check the version. The conda installation process as written on the installation instructions must be broken. We will try to figure out an alternate installation method, confirm we have the newest version, and try again.

Thanks,
Michael

**Comment by marcelm** [comment]
Indeed, the installation instructions need to be adjusted. At the moment, they recommend using `conda install whatshap`, which installs WhatsHap into the Conda base environment. Other already installed libraries or tools in that environment may conflict with the most recent WhatsHap version, which is possibly why Conda chose to install the old version.

I will update the instructions to recommend installation into a separate environment. That would look like this: `conda create -n whatshap whatshap`. Then the environment needs to be activated via `conda activate whatshap`

**Comment by michaeljmetzger** [comment]
I was installing it in a new conda environment named whatshap, but it still defaulted to the old version for some reason. It is possible that since I didn't have the bioconda channel configured that it chose the earlier version, but when I forced whatshap=1.6 it gave me an error until I installed bioconda.

**Comment by marcelm** [comment]
If you want to provide the Bioconda channel on the command line with `-c`, you also need to provide the `conda-forge` channel at the same time. So this should have worked:
```
conda create -n whatshap -c conda-forge -c bioconda whatshap
```
The Bioconda folks recently updated the [installation instructions](http://bioconda.github.io/#usage) to make this clearer; click on the little "What if I don't want to modify my condarc?" heading on that page to see what I mean.

For some Bioconda packages, you can get away not specifying `-c conda-forge`, but WhatsHap needs it.

**Comment by marcelm** [comment]
I [updated the installation instructions](https://whatshap.readthedocs.io/en/latest/installation.html).

Strangely, `conda create -n whatshap whatshap` only gives me version 1.6 when I *do not* run the `conda config --set channel_priority strict` command (or delete the corresponding setting from `~/.condarc`) that is recommended by the Bioconda instructions. With that setting, I only get 1.4. I’ll close this issue anyway and hope that this resolves itself with updates on the Bioconda and/or conda-forge side.

**Comment by marcelm** [comment]
... and thanks for reporting
