### ISSUE TITLE
WhatsHap suddenly won't work (UnicodeDecodeError message)

### ISSUE THREAD

**Issue by rmormando** [whatshap/whatshap#428]
Hello. I'm trying to phase a tetraploid yeast genome but for some reason when I go to run it with whatshap polyphase I get this error message:

```
This is WhatsHap (polyploid) 1.7 running under Python 3.10.8
[W::vcf_parse] Contig '' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::bcf_hrec_check] Invalid contig name: ""
[W::vcf_parse] Contig '@@���' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::bcf_hrec_check] Invalid contig name: "@@���"
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/whatshap-env/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/ec2-user/anaconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/ec2-user/anaconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/cli/polyphase.py", line 514, in main
    run_polyphase(**vars(args))
  File "/home/ec2-user/anaconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/cli/polyphase.py", line 106, in run_polyphase
    PhasedVcfWriter(
  File "/home/ec2-user/anaconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/vcf.py", line 1069, in __init__
    super().__init__(in_path, command_line, out_file, include_haploid_sets)
  File "/home/ec2-user/anaconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/vcf.py", line 973, in __init__
    contigs, formats, infos = missing_headers(in_path)
  File "/home/ec2-user/anaconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/vcf.py", line 916, in missing_headers
    if record.contig not in seen_contigs:
  File "pysam/libcbcf.pyx", line 3090, in pysam.libcbcf.VariantRecord.contig.__get__
  File "pysam/libcbcf.pyx", line 174, in pysam.libcbcf.bcf_str_cache_get_charptr
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 5: invalid start byte

```

The offending contig names are not found in any of the files so I'm not sure why they are causing an issue. I also did index both the BAM and FASTA files prior to running. I have been able to use this tool just fine until now and I'm not sure what happened for it not to work anymore. If someone could explain what this error message is trying to tell me that would be great thanks!

Command used:
`whatshap polyphase --ploidy 4 --ignore-read-groups --indels --reference polished.scaffold.fasta -o phase.vcf final.vcf final.bam`

Specifications:
- whatshap version 1.7
- python version 3.10.8
- installed using conda

**Comment by marcelm** [comment]
Hi, can you check that your `final.vcf` actually is in VCF format? Try `file final.vcf`, for example. For me, that command prints `Variant Call Format (VCF) version 4.1, ASCII text, with very long lines` for VCF files and `Blocked GNU Zip Format (BGZF; gzip compatible)` for BCF or `.vcf.gz` files.
