### ISSUE TITLE
Chokes on phasing data from GIAB VCF

### ISSUE THREAD

**Issue by adadiehl** [whatshap/whatshap#443]
Phased VCF and index were retrieved from GIAB:
wget https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/latest/GRCh38/SupplementaryFiles/HG001_GRCh38_1_22_v4.2.1_benchmark_hifiasm_v11_phasetransfer.vcf.gz https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/latest/GRCh38/SupplementaryFiles/HG001_GRCh38_1_22_v4.2.1_benchmark_hifiasm_v11_phasetransfer.vcf.gz.tbi 

- WhatsHap 1.7
-  and Python version 3.10.8

- How you installed the tool conda

- Which command-line parameters you used
 "whatshap haplotag --ignore-read-groups --no-reference ../data/HG001_GRCh38_1_22_v4.2.1_benchmark_hifiasm_v11_phasetransfer.vcf.gz ../data/SRR13615770.sorted.bam --skip-missing-contigs -o HG001.COMBINED.whatshap_phasing_results.bam --output-haplotag-list HG001.COMBINED.whatshap_phasing_results.txt"

Traceback (most recent call last):
  File "/data/software/Anaconda3/2022.10/envs/WhatsHap_env/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/data/software/Anaconda3/2022.10/envs/WhatsHap_env/lib/python3.10/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/data/software/Anaconda3/2022.10/envs/WhatsHap_env/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 672, in main
    run_haplotag(**vars(args))
  File "/data/software/Anaconda3/2022.10/envs/WhatsHap_env/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 589, in run_haplotag
    (BX_tag_to_haplotype, read_to_haplotype, n_mult) = prepare_haplotag_information(
  File "/data/software/Anaconda3/2022.10/envs/WhatsHap_env/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 176, in prepare_haplotag_information
    variantpos_to_phaseinfo, variants = get_variant_information(variant_table, sample)
  File "/data/software/Anaconda3/2022.10/envs/WhatsHap_env/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 100, in get_variant_information
    phase_info = int(phase.block_id), phase.phase
ValueError: invalid literal for int() with base 10: 'PATMAT'

**Comment by marcelm** [comment]
Interesting. It turns out that this is actually an [issue with the GIAB VCFs](https://github.com/genome-in-a-bottle/giab_latest_release/issues/15). The `PS` (phase set) format field needs to be of type "Integer" according to the [VCF specification](http://samtools.github.io/hts-specs/VCFv4.2.pdf), but it is "String" in that file. According to the linked issue, the files in version 4.2.1 of the GIAB release were supposed to be fixed, but that is apparently not the case.

I’m not sure whether there’s anything actionable from our side. WhatsHap could definitely print a better error message, but I don’t think we should add support for reading these files. I’m not sure what to recommend you could do. Maybe you should comment on the issue?

**Comment by adadiehl** [comment]
That was also my gut feeling, based, as you pointed out, on the VCF
specification. Given that, I guess it's a judgement call on whether or not
to relax that requirement. It does seem like GIAB would have been better
off sticking to the standard and storing the string data elsewhere instead
of overloading a commonly-used standardized field. While I doubt it will
make much impact, I will make sure to bring this directly to the attention
of the GIAB team. In the mean time, I guess I'll try transliterating the PS
tags into integers and hope for the best. Glad I only have to do it once!

Cheers,
Adam
