### ISSUE TITLE
whatshap phases first chromosome, then has a BGZF error with subsequent chromosomes

### ISSUE THREAD

**Issue by ericksonp** [whatshap/whatshap#462]
Hi, I am using Whatshap v. 1.7 and Python v. 3.9.13. It was installed on a university cluster so I'm not sure how it was installed. I have tried multiple approaches to phasing my file, and no matter what I do, I can get the first chromosome ("Scaffold_1"), to phase just fine but then run into errors with the other chromosomes (Scaffold_2 to 5). This occurs when using bam files containing all the reads, and also when providing a bam file containing just the reads for a single chromosome (produced with samtools view). My code and error output are below, showing that Scaffold_1 completed successfully but then ran into issues with Scaffold_2 . I have tried using Picard ValidateSamFile to make sure the .bam file looks okay, and it does not detect any errors (in either the whole-genome bam or the single-chromosome bam). I would really appreciate any tips or advice on how to troubleshoot this; I have tried everything I can think of! Thanks,
Priscilla

Code I used:

The bam files were generated with bwa, had readgroups added with Picard, and finally were indexed with samtools and/or Picard (have tried with both and had issues either way). 

```
whatshap phase \
-o /scratch/perickso/private/ind_seq/popgen/zaprionus.individual.2023.${samp}.phased.vcf \
 --reference=/scratch/perickso/private/ref/PO1791_Zaprionus_indianus.RepeatMasked.fasta.gz \
 /scratch/perickso/private/ind_seq/popgen/zaprionus.individual.2023.${samp}.recode.vcf.gz \
 /scratch/perickso/private/ind_seq/RGSM_final_bams/${samp}.RG.bam
```

Output:
``` 
# Working on contig Scaffold_1 in individual ZAP_3_A5
Found 58611 usable heterozygous variants (2427 skipped due to missing genotypes)
Found 503289 reads covering 58611 variants
Kept 254828 reads that cover at least two variants each
Selected 152629 most phase-informative reads covering 51757 variants
Best-case phasing would result in 8507 non-singleton phased blocks (0 singletons). 
Phasing 1 sample by solving the MEC problem ...
Largest block contains 132 variants (0.3% of accessible variants) between position 4405472 and 4413439
WARNING: Ignoring existing phasing information found in input VCF (PS tag exists).

# Working on contig Scaffold_2 in individual ZAP_3_A5
Found 48940 usable heterozygous variants (2409 skipped due to missing genotypes)
Traceback (most recent call last):
  File "/home/perickso/.local/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/home/perickso/.local/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/perickso/.local/lib/python3.9/site-packages/whatshap/cli/phase.py", line 1169, in main
    run_whatshap(**vars(args))
  File "/home/perickso/.local/lib/python3.9/site-packages/whatshap/cli/phase.py", line 493, in run_whatshap
    readset, vcf_source_ids = phased_input_reader.read(
  File "/home/perickso/.local/lib/python3.9/site-packages/whatshap/cli/__init__.py", line 152, in read
    readset = readset_reader.read(chromosome, variants, bam_sample, reference, regions)
  File "/home/perickso/.local/lib/python3.9/site-packages/whatshap/variants.py", line 98, in read
    readset = self._make_readset_from_grouped_reads(grouped_reads)
  File "/home/perickso/.local/lib/python3.9/site-packages/whatshap/variants.py", line 104, in _make_readset_from_grouped_reads
    for group in groups:
  File "/home/perickso/.local/lib/python3.9/site-packages/whatshap/variants.py", line 119, in _group_paired_reads
    for read in reads:
  File "/home/perickso/.local/lib/python3.9/site-packages/whatshap/variants.py", line 166, in _alignments_to_reads
    reference = reference[:]
  File "/home/perickso/.local/lib/python3.9/site-packages/pyfaidx/__init__.py", line 920, in __getitem__
    return self._fa.get_seq(self.name, start + 1, stop)[::step]
  File "/home/perickso/.local/lib/python3.9/site-packages/pyfaidx/__init__.py", line 1149, in get_seq
    seq = self.faidx.fetch(name, start, end)
  File "/home/perickso/.local/lib/python3.9/site-packages/pyfaidx/__init__.py", line 727, in fetch
    seq = self.from_file(name, start, end)
  File "/home/perickso/.local/lib/python3.9/site-packages/pyfaidx/__init__.py", line 769, in from_file
    self.file.seek(i.offset)
  File "/home/perickso/.local/lib/python3.9/site-packages/Bio/bgzf.py", line 682, in seek
    self._load_block(start_offset)
  File "/home/perickso/.local/lib/python3.9/site-packages/Bio/bgzf.py", line 643, in _load_block
    block_size, self._buffer = _load_bgzf_block(handle, self._text)
  File "/home/perickso/.local/lib/python3.9/site-packages/Bio/bgzf.py", line 444, in _load_bgzf_block
    raise ValueError(
ValueError: A BGZF (e.g. a BAM file) block should start with b'\x1f\x8b\x08\x04', not b'\xfd\xc7k\x1b'; handle.tell() now says 506
```

**Comment by ericksonp** [comment]
Thank you so much for the speedy response! Strangely, the `zcat` command you suggested did not print any errors, but using the original `.fasta` file (instead of the `fasta.gz` file) works. I have used that `fasta.gz` file for lots of other programs, so I'm not sure what the issue is, but very glad to have a simple solution! And, I have no recollection of installing whatshap but I probably did :) .  Thanks again, so very much!

**Comment by marcelm** [comment]
Ah ok, maybe the error message is even more misleading than I thought ... good that you found a solution that works! I’ll close this issue, feel free to open a new one if you have other questions or problems.
