### ISSUE TITLE
`AssertionError`

### ISSUE THREAD

**Issue by bounlu** [whatshap/whatshap#466]
```
Command error:
  Using whatshap for phasing
  This is WhatsHap 1.7 running under Python 3.9.0
  Working on 1 sample from 1 family
  # Working on contig chrX in individual SAMPLE
  Found 88611 usable heterozygous variants (0 skipped due to missing genotypes)
  Found 664253 reads covering 87485 variants
  Kept 72677 reads that cover at least two variants each
  Selected 71644 most phase-informative reads covering 30952 variants
  Phasing 1 sample by solving the MEC problem ...
  Largest block contains 31 variants (0.1% of accessible variants) between position 52861426 and 52862246
  Changed 376 genotypes while writing VCF
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/whatshap", line 10, in <module>
      sys.exit(main())
    File "/home/epi2melabs/conda/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
      module.main(args)
    File "/home/epi2melabs/conda/lib/python3.9/site-packages/whatshap/cli/phase.py", line 1169, in main
      run_whatshap(**vars(args))
    File "/home/epi2melabs/conda/lib/python3.9/site-packages/whatshap/cli/phase.py", line 449, in run_whatshap
      for variant_table in timers.iterate("parse_vcf", vcf_reader):
    File "/home/epi2melabs/conda/lib/python3.9/site-packages/whatshap/timer.py", line 55, in iterate
      self.stop(stage)
    File "/home/epi2melabs/conda/lib/python3.9/site-packages/whatshap/timer.py", line 21, in stop
      assert t > 0
  AssertionError
```

**Comment by marcelm** [comment]
Hi, sorry for the delay. This error happens because a runtime measurement was not positive. This is a bit weird, but I guess can happen once in a while due to the way the system clock works. Do you see this problem consistently or has it occurred only once?

**Comment by marcelm** [comment]
I’ve changed WhatsHap so that it no longer crashes, but instead just prints a warning. The runtime measurements are for statistics only anyway, so it’s fine to ignore weird measurements.
