### ISSUE TITLE
bam files not being recognized correctly

### ISSUE THREAD

**Issue by pdimens** [whatshap/whatshap#495]
Hello, I'm trying to use `whathap haplotag` to phase a BAM file from a phased VCF and I'm getting an error suggesting that the BAM file is incorrectly formatted:
```
Found 2 sample(s) in input VCF
Keeping 1 sample(s) for haplo-tagging
Found 1 sample(s) in BAM file
WARNING: Skipping duplicated position 92 on chromosome '2R' Hiding further warnings of this type, use --debug to show
Found 1543 reads covering 2418 variants
Traceback (most recent call last):
  File "/home/pdimens/conda/envs/harpy/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 676, in main
    run_haplotag(**vars(args))
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 592, in run_haplotag
    (BX_tag_to_haplotype, read_to_haplotype, n_mult) = prepare_haplotag_information(
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 177, in prepare_haplotag_information
    read_set, _ = phased_input_reader.read(
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/whatshap/cli/__init__.py", line 152, in read
    readset = readset_reader.read(chromosome, variants, bam_sample, reference, regions)
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/whatshap/variants.py", line 160, in read
    readset = self._make_readset_from_grouped_reads(grouped_reads)
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/whatshap/variants.py", line 166, in _make_readset_from_grouped_reads
    for group in groups:
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/whatshap/variants.py", line 181, in _group_paired_reads
    for read in reads:
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/whatshap/variants.py", line 228, in _alignments_to_reads
    reference = reference[:]
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/pyfaidx/__init__.py", line 924, in __getitem__
    return self._fa.get_seq(self.name, start + 1, stop)[::step]
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/pyfaidx/__init__.py", line 1153, in get_seq
    seq = self.faidx.fetch(name, start, end)
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/pyfaidx/__init__.py", line 731, in fetch
    seq = self.from_file(name, start, end)
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/pyfaidx/__init__.py", line 773, in from_file
    self.file.seek(i.offset)
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/Bio/bgzf.py", line 682, in seek
    self._load_block(start_offset)
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/Bio/bgzf.py", line 643, in _load_block
    block_size, self._buffer = _load_bgzf_block(handle, self._text)
  File "/home/pdimens/conda/envs/harpy/lib/python3.10/site-packages/Bio/bgzf.py", line 444, in _load_bgzf_block
    raise ValueError(
ValueError: A BGZF (e.g. a BAM file) block should start with b'\x1f\x8b\x08\x04', not b'\xef\x82\xbf\xa9'; handle.tell() now says 389
```

However, the bam file is correctly formatted according to samtools:
```
➜ samtools stats bam/sample1.bam | head
# This file was produced by samtools stats (1.17+htslib-1.17) and can be plotted using plot-bamstats
# This file contains statistics for all reads.
# The command line was:  stats bam/sample1.bam
# CHK, Checksum [2]Read Names   [3]Sequences    [4]Qualities
# CHK, CRC32 of reads which passed filtering followed by addition (32bit overflow)
CHK     54dce6d6        f4eb3aba        d6a8d666
# Summary Numbers. Use `grep ^SN | cut -f 2-` to extract this part.
SN      raw total sequences:    65940   # excluding supplementary and secondary reads
SN      filtered sequences:     0
SN      sequences:      65940
```
here is the header of the alignment file, for additional context:
```
➜ samtools head bam/sample1.bam
@HD     VN:1.6  SO:coordinate
@SQ     SN:2R   LN:25286936
@SQ     SN:3L   LN:28110227
@RG     ID:sample1      SM:sample1
@PG     ID:bwa  PN:bwa  VN:0.7.17-r1188 CL:bwa mem -C -t 4 -R @RG\tID:sample1\tSM:sample1 -o sample1.sam ../genome/genome.fasta.gz sample1.F.fq.gz sample1.R.fq.gz
@PG     ID:samtools     PN:samtools     PP:bwa  VN:1.17 CL:samtools view -h -q 20 -F 4 -O BAM sample1.sam
@PG     ID:samtools.1   PN:samtools     PP:samtools     VN:1.17 CL:samtools sort -O bam -o sample1.bam
```

**Comment by marcelm** [comment]
Maybe https://github.com/whatshap/whatshap/issues/462#issuecomment-1560576341 applies here?

**Comment by pdimens** [comment]
@marcelm yep, that's what did it. The error message was quite misleading. I think it's safe to close this, thank you for the help.

**Comment by marcelm** [comment]
Could you perhaps make your `.fasta.gz` file available to me and/or tell me how you created it? I’m trying to make WhatsHap print a better error message, but need an example file that I can test this on. So far, I haven’t been able to recreate a file that triggers the message.
