### ISSUE TITLE
whatshap compare does not work with the results from beagle

### ISSUE THREAD

**Issue by Zhiiiiiaozhao** [whatshap/whatshap#513]
I am using the whatshap compare to compare the results I got from beagle with the benchmark. But I got error like this:

Traceback (most recent call last):
  File "/usr/local/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/usr/local/lib/python3.9/site-packages/whatshap/cli/compare.py", line 1077, in main
    run_compare(**vars(args))
  File "/usr/local/lib/python3.9/site-packages/whatshap/cli/compare.py", line 918, in run_compare
    ) = compare(
  File "/usr/local/lib/python3.9/site-packages/whatshap/cli/compare.py", line 491, in compare
    ) = compare_pair(
  File "/usr/local/lib/python3.9/site-packages/whatshap/cli/compare.py", line 557, in compare_pair
    if hamming(phasing0, phasing1) < hamming(phasing0[0], complement(phasing1[0])):
  File "/usr/local/lib/python3.9/site-packages/whatshap/cli/compare.py", line 115, in complement
    return "".join(t[c] for c in s)
  File "/usr/local/lib/python3.9/site-packages/whatshap/cli/compare.py", line 115, in <genexpr>
    return "".join(t[c] for c in s)
KeyError: '2'

`whatshap compare --tsv-pairwise beagle_pacbio_HG005.tsv --switch-error-bed beagle_pacbio_HG005.switch_error.bed --longest-block-tsv beagle_pacbio_HG005.longest_block.tsv HG005_benchmark.chr4.vcf.gz HG005_beagle_pacbio.vcf.gz`

[HG005_beagle_pacbio.vcf.gz](https://github.com/whatshap/whatshap/files/14100147/HG005_beagle_pacbio.vcf.gz)
[HG005_benchmark.chr4.vcf.gz](https://github.com/whatshap/whatshap/files/14100149/HG005_benchmark.chr4.vcf.gz)

this works well for the phased results from other tools, shapeit and eagle, of course the whatshap.

Could you please have a look at this?

**Comment by tobiasmarschall** [comment]
Thanks for reporting this. I took a look and it's caused by multi-allelic sites (genotypes `1|2`, `2|0`, `2|1`). If you strip them from the VCF it works, I just tried this:
```
zcat HG005_beagle_pacbio.vcf.gz |grep -Ev '(1\|2|2\|0|2\|1)' |bgzip > HG005_beagle_pacbio_modified.vcf.gz
```
And the modied VCF runs fine. Of course whatshap should behave differently and handle this properly (at least ignore these variants or give a proper error message).

**Comment by Jerry-is-a-mouse** [comment]
@tobiasmarschall Hi! Is there any better method to solve this bug rather than exclude "1|2" and "2|1"? For example, transfer them back to "1/2" is suitable? I had tried two vcf files both facing with this bug.

**Comment by tobiasmarschall** [comment]
@rickymagner We'd need to look into this, but we might be in a much better position to implement this once PR #545 is merged. CC @nkkarpov @marcelm

**Comment by nkkarpov** [comment]
The easiest solution is to set mav to False [compare.py](https://github.com/whatshap/whatshap/blob/f3c644fc48bd880f22b9575d419bc116a0f5acfc/whatshap/cli/compare.py#L766-L768). In this case, compare will ignore all mav variants. Although this might not be the expected behavior, it is preferable to a crash. We could incorporate the logic I used in the haplotagphase command, which maps an allele to 0/1 (for the diploid case) and back. However, I am uncertain how to handle cases where two VCF files have different genotypes, such as 0/1 and 1/2. Due to the low number of mav events in the diploid case, this is not a significant loss.

**Comment by nkkarpov** [comment]
I have implemented the 'easy fix' in https://github.com/whatshap/whatshap/pull/571

**Comment by rickymagner** [comment]
I think it would make sense to at least print a clear warning if certain sites are being skipped in the comparison. Would it make sense to even split a het MA into two separate het entries? I know that the tool also crashes though if you have sites with the same POS across rows, so I wonder if addressing that might actually resolve it as well?

**Comment by nkkarpov** [comment]
Currently, WhatsHap doesn't issue any warnings when it ignores Mav, which could occur in various cases (for example, phasing in the diploid case). I suggest separating this into different MRs.

Your question already contains the answer: no, it won’t help. I’m certain that the right approach is to handle Mav natively and incorporate the logic around it in multiple places (and unify it, of course). However, as I understand, this would require some adjustments in the C++ backend, which assumes genotype 0/1. A possible solution might be to convert the genotype to the 0/1 format before processing it and then revert it back to its original form.

**Comment by rickymagner** [comment]
Thanks for the reply. What do you mean convert the GT to 0/1 before processing? If it's an MA site, wouldn't that be destroying information?

**Comment by nkkarpov** [comment]
It shouldn't. You can take a look at https://github.com/whatshap/whatshap/pull/545 and specifically on  https://github.com/whatshap/whatshap/pull/545#discussion_r1829197387.
