### ISSUE TITLE
haplotag polyploidy ValueError

### ISSUE THREAD

**Issue by yeonjin968** [whatshap/whatshap#526]
Hello, 

Before asking about the problem, I wrote down the basic information below,

- Versions : WhatsHap(2.2) Python(3.10.14)
- I installed WhatsHap via conda
- command-line parameters I used : `whatshap haplotag -o {bam_file} --output-threads 12 --no-reference --ploidy 3  {input.vcf} {sample.mkdup.bam}` 

When I tried to run haplotag for polyploidy sample, I got an error like below.

Traceback (most recent call last):
  File "/home/users/yeonjin/miniconda/231121/miniconda3/envs/whatshap-env/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/users/yeonjin/miniconda/231121/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/users/yeonjin/miniconda/231121/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 683, in main
    run_haplotag(**vars(args))
  File "/home/users/yeonjin/miniconda/231121/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 582, in run_haplotag
    variant_table = load_chromosome_variants(vcf_reader, chrom, regions)
  File "/home/users/yeonjin/miniconda/231121/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 147, in load_chromosome_variants
    variant_table = vcf_reader.fetch_regions(chromosome, regions)
  File "/home/users/yeonjin/miniconda/231121/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/vcf.py", line 580, in fetch_regions
    return self._process_single_chromosome(chromosome, records)
  File "/home/users/yeonjin/miniconda/231121/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/vcf.py", line 684, in _process_single_chromosome
    p = extract_phase(call)
  File "/home/users/yeonjin/miniconda/231121/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/vcf.py", line 602, in _extract_HP_phase
    phase = tuple(phase[order.index(i)] for i in range(len(order)))
  File "/home/users/yeonjin/miniconda/231121/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/vcf.py", line 602, in <genexpr>
    phase = tuple(phase[order.index(i)] for i in range(len(order)))
ValueError: 2 is not in list

I think this error occurred because the GT field in input vcf file does not contain 2.
However, this error didn't occurred when I ran the whatshap haplotag for another sample with same vcf format.

Here is the vcf file I used as input file. 
[Per01.hr2.phased.vcf.gz](https://github.com/whatshap/whatshap/files/14903866/Per01.hr2.phased.vcf.gz)

Could you please have a look at this?

**Comment by marcelm** [comment]
Can you provide a BAM file as well so that we can reproduce the problem?

**Comment by yeonjin968** [comment]
Thanks for your quick response! I sent the BAM file to the email address on your profile.

**Comment by schrins** [comment]
To me it looks like the writing routine for HP tags is indeed incorrect for polyploid phases. However, I am not entirely sure what the correct encoding would be in the polyploid case. For a quick workaround I would suggest to use PS tags as well. I am still quite busy for the next two weeks, so I will likely not fix this bug until then.
