### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 5: invalid start byte

### ISSUE THREAD

**Issue by pdimens** [whatshap/whatshap#533]
- python: 3.10.14
  - whatshap: 2.2
- How you installed the tool (conda, pip)
  - conda
- Which command-line parameters you used
```bash
whatshap haplotag --ignore-read-groups --sample sample2 --tag-supplementary --output-threads=4 -o output/sample2.bam --reference genome.fasta test.phased.bcf input/sample2.bam 2> sample2.phase.log
```
Full error log:
```
Found 2 sample(s) in input VCF
Keeping 1 sample(s) for haplo-tagging
Found 1 sample(s) in BAM file
WARNING: Skipping duplicated position 92 on chromosome '2R' Hiding further warnings of this type, use --debug to show
Traceback (most recent call last):
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 683, in main
    run_haplotag(**vars(args))
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 599, in run_haplotag
    (BX_tag_to_haplotype, read_to_haplotype, n_mult) = prepare_haplotag_information(
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/whatshap/cli/haplotag.py", line 177, in prepare_haplotag_information
    read_set, _ = phased_input_reader.read(
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/whatshap/cli/__init__.py", line 152, in read
    readset = readset_reader.read(chromosome, variants, bam_sample, reference, regions)
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/whatshap/variants.py", line 160, in read
    readset = self._make_readset_from_grouped_reads(grouped_reads)
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/whatshap/variants.py", line 166, in _make_readset_from_grouped_reads
    for group in groups:
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/whatshap/variants.py", line 181, in _group_paired_reads
    for read in reads:
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/whatshap/variants.py", line 228, in _alignments_to_reads
    reference = reference[:]
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/pyfaidx/__init__.py", line 914, in __getitem__
    return self._fa.get_seq(self.name, start + 1, stop)[::step]
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/pyfaidx/__init__.py", line 1143, in get_seq
    seq = self.faidx.fetch(name, start, end)
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/pyfaidx/__init__.py", line 721, in fetch
    seq = self.from_file(name, start, end)
  File "/home/runner/work/harpy/harpy/.snakemake/conda/46127eb8d0a94387801fd43cff1f9b9c_/lib/python3.10/site-packages/pyfaidx/__init__.py", line 775, in from_file
    seq = self.file.read(seq_blen).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 5: invalid start byte
```

**Comment by pdimens** [comment]
This issue was resolved by discovering the fasta file wasn't decompressed from its original `.fasta.gz`
