### ISSUE TITLE
BAM file reading issue for haplotagphase

### ISSUE THREAD

**Issue by pdimens** [whatshap/whatshap#534]
- WhatsHap and Python version (`python -V` and `whatshap --version`)
  - `whatshap`: 2.3
  - `python`: 3.10.14 
- How you installed the tool (conda, pip)
  - conda
- Which command-line parameters you used
```bash
whatshap haplotagphase --reference genome.fasta.gz test/vcf/test.bcf samples.bam > test.vcf
```
## The issue
Despite reading the bam file (it outputs that it know how many reads/alignments support how many variants), it keeps giving a BAM file reading error.

## The output
```
Processing chromosome 2R...
Processing sample sample2
Number of supplementary alignments: 0
Number of non-singleton groups: 3546
Skipped 0 groups
Found 8732 reads covering 15333 variants
Number of homozygous variants is 16417
Number of already phased variants is 0
Processing sample sample1
Number of supplementary alignments: 0
Number of non-singleton groups: 3600
Skipped 0 groups
Found 9198 reads covering 15650 variants
Number of homozygous variants is 17065
Number of already phased variants is 0
WARNING: Skipping duplicated position 2177721 on chromosome '3L' Hiding further warnings of this type, use --debug to show
Processing chromosome 3L...
Processing sample sample2
Traceback (most recent call last):
  File "/home/pdimens/conda/envs/whatshap/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/whatshap/cli/haplotagphase.py", line 351, in main
    run_haplotagphase(**vars(args))
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/whatshap/cli/haplotagphase.py", line 117, in run_haplotagphase
    reads, _ = phased_input_reader.read(chromosome, variant_table.variants, sample)
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/whatshap/cli/__init__.py", line 152, in read
    readset = readset_reader.read(chromosome, variants, bam_sample, reference, regions)
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/whatshap/variants.py", line 180, in read
    readset = self._make_readset_from_grouped_reads(grouped_reads)
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/whatshap/variants.py", line 186, in _make_readset_from_grouped_reads
    for group in groups:
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/whatshap/variants.py", line 263, in _group_reads
    for read in reads:
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/whatshap/variants.py", line 319, in _alignments_to_reads
    reference = reference[:]
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/pyfaidx/__init__.py", line 914, in __getitem__
    return self._fa.get_seq(self.name, start + 1, stop)[::step]
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/pyfaidx/__init__.py", line 1143, in get_seq
    seq = self.faidx.fetch(name, start, end)
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/pyfaidx/__init__.py", line 721, in fetch
    seq = self.from_file(name, start, end)
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/pyfaidx/__init__.py", line 763, in from_file
    self.file.seek(i.offset)
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/Bio/bgzf.py", line 683, in seek
    self._load_block(start_offset)
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/Bio/bgzf.py", line 644, in _load_block
    block_size, self._buffer = _load_bgzf_block(handle, self._text)
  File "/home/pdimens/conda/envs/whatshap/lib/python3.10/site-packages/Bio/bgzf.py", line 444, in _load_bgzf_block
    raise ValueError(
ValueError: A BGZF (e.g. a BAM file) block should start with b'\x1f\x8b\x08\x04', not b'V3j\xbb'; handle.tell() now says 38
```

**Comment by marcelm** [comment]
The error message is most likely misleading: The BGZF file in this case is probably the BCF file. Both BAM and BCF files are BGZF compressed, which is why the error message mentions that.

(It could also be the reference FASTA if bgzip was used to compress it.) 

See https://github.com/whatshap/whatshap/issues/462#issuecomment-1560576341

I suggest that you try `bcftools view` on the `.bcf` file to see whether there is a problem with it.

**Comment by pdimens** [comment]
Thanks for the speedy response. The compressed `fasta` file seemed to be triggering the issue. Does a bgzipped fasta file not work with this command?

**Comment by marcelm** [comment]
It just found https://github.com/whatshap/whatshap/issues/151 where we found out that it used to be the case that the index required by pyfaidx is not compatible with the one created by `samtools faidx`. I thought that issue has been solved, will need to read a bit more later.

**Comment by marcelm** [comment]
A bgzipped FASTA should work fine. Can you share the file(s) or the commands you used to create and index them so we can see for ourselves what is going on?

**Comment by pdimens** [comment]
Sure. 
fasta file: https://github.com/pdimens/harpy/blob/dev/test/genome/genome.fasta.gz
bam files: https://github.com/pdimens/harpy/tree/dev/test/bam
  - were combined with `samtools merge` for testing
vcf: https://github.com/pdimens/harpy/blob/dev/test/vcf/test.bcf

**Comment by marcelm** [comment]
Awesome, thanks, I was able to reproduce the error message now. I’ll look into this, but won’t have more time today.
