### ISSUE TITLE
Ploidy error

### ISSUE THREAD

**Issue by eesiribloom** [whatshap/whatshap#552]
I am running this command to phase the tumour bam file with illumina germline SNVs. The sample is from a female. 
```
whatshap phase \
-o Sample_phased.vcf \
--reference GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
/path/to/Sample-normal-gatk-haplotype-annotated.vcf.gz \
path/to/Sample-tumour-aligned.bam \
--ignore-read-groups 
```

I get this output:
```
WARNING: Ignoring --row-limit as heuristic is not used as algorithm.
This is WhatsHap 2.2 running under Python 3.9.18
Working on 1 sample from 1 family
...
# Working on contig chrX in individual SHGSOC080N
Found 74083 usable heterozygous variants (0 skipped due to missing genotypes)
Found 428601 reads covering 73894 variants
Kept 250898 reads that cover at least two variants each
Selected 112698 most phase-informative reads covering 73104 variants
Best-case phasing would result in 1604 non-singleton phased blocks (0 singletons). 
Phasing 1 sample by solving the MEC problem ...
Largest block contains 1593 variants (2.2% of accessible variants) between position 242414 and 991712
Traceback (most recent call last):
  File "/usr/local/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/usr/local/lib/python3.9/site-packages/whatshap/cli/phase.py", line 1195, in main
    run_whatshap(**vars(args))
  File "/usr/local/lib/python3.9/site-packages/whatshap/cli/phase.py", line 451, in run_whatshap
    for variant_table in timers.iterate("parse_vcf", vcf_reader):
  File "/usr/local/lib/python3.9/site-packages/whatshap/timer.py", line 58, in iterate
    for item in iterator:
  File "/usr/local/lib/python3.9/site-packages/whatshap/vcf.py", line 589, in __iter__
    yield self._process_single_chromosome(chromosome, records)
  File "/usr/local/lib/python3.9/site-packages/whatshap/vcf.py", line 747, in _process_single_chromosome
    raise PloidyError(
whatshap.vcf.PloidyError: Inconsistent ploidy (2 and 1)
```
I skipped the other chromosomes (1-22) which seem to work fine.
I would've expected this to be an issue in male samples with a haploid X chromosome so I am a bit confused.

**Comment by eesiribloom** [comment]
Turns out that whilst the VCF file contained mostly heterozygous variants marked as diploid, the presence of any (even if a relatively small number) of haploid variants causes an error instead of being skipped.
