### ISSUE TITLE
KeyError: 2 when running `compare` on HiPhase input

### ISSUE THREAD

**Issue by rickymagner** [whatshap/whatshap#570]
Hi, I received this error when running `whatshap compare` on some HiPhase VCFs:
```
Traceback (most recent call last):
File "/usr/local/bin/whatshap", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/local/lib/python3.12/dist-packages/whatshap/__main__.py", line 64, in main
Comparing phasings for samples: HG002, SAMPLE (--ignore-sample-names selected)
FILENAMES
truth = fixed_ploidy-base-norm.vcf.gz
callset = fixed_ploidy-call-norm.vcf.gz
---------------- Chromosome chr1 ----------------
VARIANT COUNTS (heterozygous / all):
truth: 292704 / 445256
callset: 309531 / 512312
UNION: 390966 / 604812
INTERSECTION: 211269 / 352756
PAIRWISE COMPARISON: truth <--> callset:
common heterozygous variants: 211269
(restricting to these below)
non-singleton blocks in truth: 1
--> covered variants: 207862
non-singleton blocks in callset: 2307
--> covered variants: 201181
non-singleton intersection blocks: 2267
--> covered variants: 198975
module.main(args)
File "/usr/local/lib/python3.12/dist-packages/whatshap/cli/compare.py", line 1078, in main
run_compare(**vars(args))
File "/usr/local/lib/python3.12/dist-packages/whatshap/cli/compare.py", line 919, in run_compare
) = compare(
^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/whatshap/cli/compare.py", line 492, in compare
) = compare_pair(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/whatshap/cli/compare.py", line 558, in compare_pair
if hamming(phasing0, phasing1) < hamming(phasing0[0], complement(phasing1[0])):
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/whatshap/cli/compare.py", line 116, in complement
return "".join(t[c] for c in s)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/whatshap/cli/compare.py", line 116, in <genexpr>
return "".join(t[c] for c in s)
~^^^
KeyError: '2'
```

Here are two sample lines from the VCF, though it's not clear if these are causing the problem or other variants further in.
```
chr1    10146   .       AC      A       42.92   PASS    AC=1;AF=0.5;AN=2;DP=24;FS=0;MQ=25.45;MQRankSum=0.8;QD=1.79;ReadPosRankSum=-2;SOR=0.694;FractionInformativeReads=0.583;R2_5P_bias=12.205 GT:AD:AF:DP:F1R2:F2R1:GQ:PL:GP:PRI:SB:MB:PS   0|1:5,9:0.643:14:3,5:2,4:25:73,0,22:42.923,0.014411,24.866:0,30,33.01:2,3,5,4:4,1,9,0:10146
chr1    10177   .       A       AC      25.34   PASS    AC=1;AF=0.5;AN=2;DP=22;FS=0;MQ=29.49;MQRankSum=-0.794;QD=1.15;ReadPosRankSum=0.217;SOR=0.368;FractionInformativeReads=0.682;R2_5P_bias=-7.854   GT:AD:AF:DP:F1R2:F2R1:GQ:PL:GP:PRI:SB:MB:PS   0|1:3,12:0.8:15:2,7:1,5:16:31,0,13:25.335,0.11043,16.541:0,6,9.01:2,1,6,6:3,0,9,3:10146
```

Any hints on what I can try to fix this? Here are versions:
```
python: 3.12.3
whatshap 2.3 (installed via pip)
```

**Comment by tobiasmarschall** [comment]
Thanks for reporting this. Could you possibly also provide the VCF header? I.e. a small VCF file with these two lines that reproduces the error? That'd make it easier for us to debug this...

**Comment by rickymagner** [comment]
So I did some digging and actually found out it's the same as this issue here: https://github.com/whatshap/whatshap/issues/513. Removing the `1|2` sites allowed the tool to work properly, but this doesn't seem like a "fix" since I'd like those sites to be included in the comparison. Are there any other workarounds or plans to fix this in the tool?

**Comment by tobiasmarschall** [comment]
Ok, got it. Then let's continue the discussion in Issue #513.
